"""
ED KPI Query Builder — Streamlit App
All 24 KPIs × 8 HIS systems (MCC, CAREWARE, OASIS, VIDAPLUS, ARCUSAIR, VIDA, INTERSYSTEM, EPIC)
Source pattern: SW_EMERGENCY raw HIS join CTEs (v8)
"""

import streamlit as st
from datetime import date, timedelta

# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="ED KPI Query Builder",
    page_icon="🏥",
    layout="wide",
)

LU = "NMR.ANALYTICS.LU_DISCH_DEST_EMERGENCY"

# ─────────────────────── helpers ─────────────────────────────────────────────

def gran_col(g: str) -> str:
    if g == "Daily":
        return "e.PATIENT_VISIT_DATETIME::DATE                        AS Visit_Date"
    if g == "Weekly":
        return "DATE_TRUNC('week',  e.PATIENT_VISIT_DATETIME::DATE)   AS Visit_Week"
    return "DATE_TRUNC('month', e.PATIENT_VISIT_DATETIME::DATE)   AS Visit_Month"

def gran_grp(g: str) -> str:
    if g == "Daily":
        return "e.PATIENT_VISIT_DATETIME::DATE"
    if g == "Weekly":
        return "DATE_TRUNC('week',  e.PATIENT_VISIT_DATETIME::DATE)"
    return "DATE_TRUNC('month', e.PATIENT_VISIT_DATETIME::DATE)"

def src_alias(hf: str, ff: str) -> str:
    return "SW_FILTERED" if (hf != "ALL" or ff) else "SW_EMERGENCY"

def cte_prefix(df: str, dt: str, hf: str, ff: str) -> str:
    hi = f"\n  AND HIS = '{hf}'" if hf != "ALL" else ""
    fa = f"\n  AND FACILITY_CODE_NHIC = '{ff}'" if ff else ""
    # upper-bound filter on the outer SW_FILTERED or SW_EMERGENCY wrapper
    da = f"\n  AND PATIENT_VISIT_DATETIME::DATE <= {dt}" if dt else ""
    body = cte_body(df, dt)
    if hi or fa or da:
        return f"WITH {body},\n\nSW_FILTERED AS (\n  SELECT * FROM SW_EMERGENCY\n  WHERE 1=1{hi}{fa}{da}\n)"
    return f"WITH {body}"

# ─────────────────────── CTE body ────────────────────────────────────────────

def cte_body(df: str, dt: str = "") -> str:
    # upper-bound clause appended to each HIS branch WHERE
    ub_visit   = f" AND CAST(em.PATIENT_VISIT_DATE_TIME AS DATE) <= {dt}" if dt else ""
    ub_visit_d = f" AND CAST(em.PATIENT_VISIT_DATE AS DATE) <= {dt}"      if dt else ""
    ub_visitd2 = f" AND CAST(em.VISITDATE AS DATE) <= {dt}"               if dt else ""
    ub_visit_i = f" AND CAST(em.VISIT_DATE AS DATE) <= {dt}"              if dt else ""
    ub_arrival = f" AND CAST(em.ARRIVALINSTANT AS DATE) <= {dt}"          if dt else ""
    ub_oasis   = f" AND CAST(VISIT_DATE_TIME AS DATE) <= {dt}"            if dt else ""
    return f"""/* ══ MCC ══════════════════════════════════════════════════════ */
MCC_LAB AS (
  SELECT ENCOUNTER_NUMBER, FACILILTY_CODE, MEDICAL_RECORD_NUMBER_MRN,
    COUNT(DISTINCT CASE WHEN UPPER(TRIM(PRIORITY))='ROUTINE' THEN LAB_ORDER_ID END)                                                          AS LAB_ORDERS_ROUTINE,
    COUNT(DISTINCT CASE WHEN UPPER(TRIM(PRIORITY))='STAT' THEN LAB_ORDER_ID||'-'||TO_VARCHAR(LAB_ODER_DATE_TIME,'YYYY-MM-DD HH24:MI:SS') END) AS LAB_ORDERS_STAT,
    AVG(CASE WHEN UPPER(TRIM(PRIORITY))='ROUTINE' THEN DATEDIFF('hour',LAB_ODER_DATE_TIME,RESULT_DATE_TIME) END)  AS ROUTINE_LAB_TAT_hours,
    AVG(CASE WHEN UPPER(TRIM(PRIORITY))='STAT'    THEN DATEDIFF('hour',LAB_ODER_DATE_TIME,RESULT_DATE_TIME) END)  AS STAT_LAB_TAT_hours,
    MIN(LAB_ODER_DATE_TIME) AS Earliest_Lab_Order_DateTime, MAX(LAB_ODER_DATE_TIME) AS Latest_Lab_Order_DateTime,
    AVG(CASE WHEN UPPER(TRIM(PRIORITY))='STAT'    THEN DATEDIFF('hour',RECEIVING_DATE_TIME,RESULT_DATE_TIME) END) AS STAT_LAB_TAT_hours_UCC
  FROM NMR.MCC.LAB GROUP BY ENCOUNTER_NUMBER, FACILILTY_CODE, MEDICAL_RECORD_NUMBER_MRN
),
MCC_RAD AS (
  SELECT r.ENCOUNTER_NUMBER, r.FACILILTY_CODE, r.MEDICAL_RECORD_NUMBER_MRN,
    SUM(CASE WHEN UPPER(TRIM(r.RAD_ORDER_PRIORITY))='ROUTINE' THEN 1 ELSE 0 END) AS RAD_ORDERS_ROUTINE,
    SUM(CASE WHEN UPPER(TRIM(r.RAD_ORDER_PRIORITY)) IN ('URGENT','ASAP','STATE','ER','STAT','EMERGENCY') THEN 1 ELSE 0 END) AS RAD_ORDERS_STAT,
    AVG(CASE WHEN UPPER(TRIM(r.RAD_ORDER_PRIORITY))='ROUTINE' THEN DATEDIFF('hour',r.PATIENT_VISIT_DATETIME,r.RAD_REPORT_DATETIME) END) AS ROUTINE_RAD_TAT_hours,
    AVG(CASE WHEN UPPER(TRIM(r.RAD_ORDER_PRIORITY)) IN ('URGENT','ASAP','STATE','ER','STAT','EMERGENCY') THEN DATEDIFF('hour',r.PATIENT_VISIT_DATETIME,r.RAD_REPORT_DATETIME) END) AS STAT_RAD_TAT_hours,
    AVG(CASE WHEN UPPER(TRIM(r.RAD_ORDER_PRIORITY)) IN ('URGENT','ASAP','STATE','ER','STAT','EMERGENCY') THEN DATEDIFF('hour',r.EXAM_START_DATETIME,r.RAD_REPORT_DATETIME) END) AS STAT_RAD_TAT_hours_UCC,
    SUM(CASE WHEN r.REQUESTED_RAD_SERVICE ILIKE '%CT%' THEN 1 ELSE 0 END) AS CT_ORDERS,
    SUM(CASE WHEN r.REQUESTED_RAD_SERVICE IN ('3035006020','03035006021','03030011855','03035005701','03035005702','03035005703','03035005495','03035006004','03035006031') THEN 1 ELSE 0 END) AS CT_ORDERS_STROKE,
    AVG(CASE WHEN r.REQUESTED_RAD_SERVICE ILIKE '%CT%' THEN DATEDIFF('hour',e.PATIENT_VISIT_DATE_TIME,r.EXAM_START_DATETIME) END) AS CT_START_TIME_hours,
    AVG(CASE WHEN r.REQUESTED_RAD_SERVICE IN ('3035006020','03035006021','03030011855','03035005701','03035005702','03035005703','03035005495','03035006004','03035006031') THEN DATEDIFF('hour',e.PATIENT_VISIT_DATE_TIME,r.EXAM_START_DATETIME) END) AS CT_HOURS_STROKE,
    MIN(r.REQUEST_DATETIME) AS Earliest_Rad_Order_DateTime, MAX(r.REQUEST_DATETIME) AS Latest_Rad_Order_DateTime
  FROM NMR.MCC.RADIOLOGY r
  LEFT JOIN NMR.MCC.EMERGENCY e ON r.ENCOUNTER_NUMBER=e.ENCOUNTER_NUMBER AND r.FACILILTY_CODE=e.FACILILTY_CODE AND r.MEDICAL_RECORD_NUMBER_MRN=e.MEDICAL_RECORD_NUMBER_MRN
  GROUP BY r.ENCOUNTER_NUMBER, r.FACILILTY_CODE, r.MEDICAL_RECORD_NUMBER_MRN
),
MCC_PHARM AS (
  SELECT ENCOUNTER_NUMBER, FACILILTY_CODE, MEDICAL_RECORD_NUMBER_MRN,
    COUNT(ENCOUNTER_NUMBER) AS C_PHARM_ORDERS, COUNT(DISPENSE_DATE_TIME) AS C_PHARM_ORDERS_COMPLETED,
    MIN(PRESCRIPTION_DATE_TIME) AS Earliest_Phar_Order_DateTime, MAX(PRESCRIPTION_DATE_TIME) AS Latest_Phar_Order_DateTime,
    MAX(MEDICINE_ADMINISTERED_DATETIME) AS Phar_Administr_DateTime
  FROM NMR.MCC.PHARMACY GROUP BY ENCOUNTER_NUMBER, FACILILTY_CODE, MEDICAL_RECORD_NUMBER_MRN
),
MCC_PT AS (
  SELECT MEDICAL_RECORD_NUMBER_MRN, FACILILTY_CODE, DATE_OF_BIRTH, GENDER, MARITAL_STATUS, NATIONALITY, RELIGION
  FROM NMR.MCC.PATIENT_PROFILE WHERE FACILILTY_CODE IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (PARTITION BY FACILILTY_CODE, MEDICAL_RECORD_NUMBER_MRN ORDER BY LAST_UPDATE_DATETIME DESC)=1
),
/* ══ CAREWARE ══════════════════════════════════════════════════════ */
CW_LAB AS (
  SELECT ENCOUNTER_NUMBER,
    SUM(CASE WHEN ATS_LAB_PRIORITY_DESC='Routine' THEN 1 ELSE 0 END) AS LAB_ORDERS_ROUTINE,
    SUM(CASE WHEN ATS_LAB_PRIORITY_DESC IN ('Urgent/Now/ASAP','STAT/Emergent') THEN 1 ELSE 0 END) AS LAB_ORDERS_STAT,
    AVG(CASE WHEN ATS_LAB_PRIORITY_DESC='Routine' THEN DATEDIFF('hour',RECEIVING_DATE,RESULT_DATE) END) AS ROUTINE_LAB_TAT_hours,
    AVG(CASE WHEN ATS_LAB_PRIORITY_DESC IN ('Urgent/Now/ASAP','STAT/Emergent') THEN DATEDIFF('hour',RECEIVING_DATE,RESULT_DATE) END) AS STAT_LAB_TAT_hours,
    MIN(LAB_ORDER_DATE) AS Earliest_Lab_Order_DateTime, MAX(LAB_ORDER_DATE) AS Latest_Lab_Order_DateTime,
    AVG(CASE WHEN ATS_LAB_PRIORITY_DESC IN ('Urgent/Now/ASAP','STAT/Emergent') THEN DATEDIFF('hour',RECEIVING_DATE,RESULT_DATE) END) AS STAT_LAB_TAT_hours_UCC
  FROM NMR.CAREWARE.LAB GROUP BY ENCOUNTER_NUMBER
),
CW_RAD AS (
  SELECT ENCOUNTER_NUMBER,
    SUM(CASE WHEN ATS_RAD_PRIORITY_DESC='Routine' THEN 1 ELSE 0 END) AS RAD_ORDERS_ROUTINE,
    SUM(CASE WHEN ATS_RAD_PRIORITY_DESC IN ('STAT/Emergent','Urgent/Now/ASAP') THEN 1 ELSE 0 END) AS RAD_ORDERS_STAT,
    AVG(CASE WHEN ATS_RAD_PRIORITY_DESC='Routine' THEN DATEDIFF('hour',PATIENT_VISIT_DATE_TIME,RAD_REPORT_DATE_TIME) END) AS ROUTINE_RAD_TAT_hours,
    AVG(CASE WHEN ATS_RAD_PRIORITY_DESC IN ('STAT/Emergent','Urgent/Now/ASAP') THEN DATEDIFF('hour',PATIENT_VISIT_DATE_TIME,RAD_REPORT_DATE_TIME) END) AS STAT_RAD_TAT_hours,
    AVG(CASE WHEN ATS_RAD_PRIORITY_DESC IN ('STAT/Emergent','Urgent/Now/ASAP') THEN DATEDIFF('hour',EXAM_START_DATE_TIME,RAD_REPORT_DATE_TIME) END) AS STAT_RAD_TAT_hours_UCC,
    SUM(CASE WHEN REQUESTED_RAD_SERVICE ILIKE '%CT%' THEN 1 ELSE 0 END) AS CT_ORDERS,
    SUM(CASE WHEN REQUESTED_RAD_SERVICE IN ('3035006020','03035006021','03030011855','03035005701','03035005702','03035005703','03035005495','03035006004','03035006031') THEN 1 ELSE 0 END) AS CT_ORDERS_STROKE,
    AVG(CASE WHEN REQUESTED_RAD_SERVICE ILIKE '%CT%' THEN DATEDIFF('hour',PATIENT_VISIT_DATE_TIME,EXAM_START_DATE_TIME) END) AS CT_START_TIME_hours,
    AVG(CASE WHEN REQUESTED_RAD_SERVICE IN ('3035006020','03035006021','03030011855','03035005701','03035005702','03035005703','03035005495','03035006004','03035006031') THEN DATEDIFF('hour',PATIENT_VISIT_DATE_TIME,EXAM_START_DATE_TIME) END) AS CT_HOURS_STROKE,
    MIN(REQUEST_DATE_TIME) AS Earliest_Rad_Order_DateTime, MAX(REQUEST_DATE_TIME) AS Latest_Rad_Order_DateTime
  FROM NMR.CAREWARE.RADIOLOGY GROUP BY ENCOUNTER_NUMBER
),
CW_PHARM AS (
  SELECT ENCOUNTER_NUMBER,
    COUNT(ENCOUNTER_NUMBER) AS C_PHARM_ORDERS, COUNT(DISPENSE_DATE) AS C_PHARM_ORDERS_COMPLETED,
    MIN(PRESCRIPTION_DATE) AS Earliest_Phar_Order_DateTime, MAX(PRESCRIPTION_DATE) AS Latest_Phar_Order_DateTime,
    MAX(DISPENSE_DATE) AS Phar_Administr_DateTime
  FROM NMR.CAREWARE.PHARMACY GROUP BY ENCOUNTER_NUMBER
),
CW_PT AS (
  SELECT MEDICAL_RECORD_NUMBER_MRN, FACILITY_CODE_NHIC, DAT_OF_BIRTH AS DATE_OF_BIRTH,
    ATS_GENDER_NAME AS GENDER, ATS_MARITAL_STATUS_NAME AS MARITAL_STATUS,
    ATS_NATIONALITY_NAME AS NATIONALITY, ATS_RELIGION_NAME AS RELIGION
  FROM NMR.CAREWARE.PATIENT_PROFILE WHERE FACILITY_CODE_NHIC IS NOT NULL
),
/* ══ ARCUSAIR ══════════════════════════════════════════════════════ */
ARC_LAB AS (
  SELECT LAB_ORDER_ID, FACILITYID AS ARC_FACILITYID, MRN,
    COUNT(DISTINCT CASE WHEN UPPER(TRIM(LAB_ORDER_PRIORITY)) IN ('ROUTINE') THEN LAB_ORDER_CODE END) AS LAB_ORDERS_ROUTINE,
    COUNT(DISTINCT CASE WHEN UPPER(TRIM(LAB_ORDER_PRIORITY)) IN ('STAT','URGENT') THEN LAB_ORDER_CODE END) AS LAB_ORDERS_STAT,
    AVG(CASE WHEN UPPER(TRIM(LAB_ORDER_PRIORITY)) IN ('ROUTINE') THEN DATEDIFF('hour',LAB_ORDER_DATETIME,RESULTDATETIME) END) AS ROUTINE_LAB_TAT_hours,
    AVG(CASE WHEN UPPER(TRIM(LAB_ORDER_PRIORITY)) IN ('STAT','URGENT') THEN DATEDIFF('hour',LAB_ORDER_DATETIME,RESULTDATETIME) END) AS STAT_LAB_TAT_hours,
    MIN(LAB_ORDER_DATETIME) AS Earliest_Lab_Order_DateTime, MAX(LAB_ORDER_DATETIME) AS Latest_Lab_Order_DateTime,
    AVG(CASE WHEN UPPER(TRIM(LAB_ORDER_PRIORITY)) IN ('STAT','URGENT') THEN DATEDIFF('hour',RECEIVINGDATETIME,RESULTDATETIME) END) AS STAT_LAB_TAT_hours_UCC
  FROM NMR.ARCUSAIR.LAB GROUP BY LAB_ORDER_ID, FACILITYID, MRN
),
ARC_RAD AS (
  SELECT r.RAB_ORDER_ID, r.FACILITYID AS ARC_FACILITYID, r.MRN,
    COUNT(DISTINCT CASE WHEN UPPER(TRIM(r.RAD_ORDER_PRIORITY)) IN ('ROUTINE') THEN r.RAB_ORDER_CODE END) AS RAD_ORDERS_ROUTINE,
    COUNT(DISTINCT CASE WHEN UPPER(TRIM(r.RAD_ORDER_PRIORITY)) IN ('STAT','URGENT') THEN r.RAB_ORDER_CODE END) AS RAD_ORDERS_STAT,
    AVG(CASE WHEN UPPER(TRIM(r.RAD_ORDER_PRIORITY))='ROUTINE' THEN DATEDIFF('hour',r.VISITDATE,r.RAD_REPORT_DATETIME) END) AS ROUTINE_RAD_TAT_hours,
    AVG(CASE WHEN UPPER(TRIM(r.RAD_ORDER_PRIORITY)) IN ('STAT','URGENT') THEN DATEDIFF('hour',r.VISITDATE,r.RAD_REPORT_DATETIME) END) AS STAT_RAD_TAT_hours,
    AVG(CASE WHEN UPPER(TRIM(r.RAD_ORDER_PRIORITY)) IN ('STAT','URGENT') THEN DATEDIFF('hour',r.EXAM_START_DATETIME,r.RAD_REPORT_DATETIME) END) AS STAT_RAD_TAT_hours_UCC,
    SUM(CASE WHEN r.REQUESTED_RAD_SERVICE ILIKE '%CT%' THEN 1 ELSE 0 END) AS CT_ORDERS,
    SUM(CASE WHEN r.REQUESTED_RAD_SERVICE_CODE IN ('3035006020','03035006021','03030011855','03035005701','03035005702','03035005703','03035005495','03035006004','03035006031') THEN 1 ELSE 0 END) AS CT_ORDERS_STROKE,
    AVG(CASE WHEN r.REQUESTED_RAD_SERVICE ILIKE '%CT%' THEN DATEDIFF('hour',arc_em.VISITDATE,r.EXAM_START_DATETIME) END) AS CT_START_TIME_hours,
    AVG(CASE WHEN r.REQUESTED_RAD_SERVICE_CODE IN ('3035006020','03035006021','03030011855','03035005701','03035005702','03035005703','03035005495','03035006004','03035006031') THEN DATEDIFF('hour',arc_em.VISITDATE,r.EXAM_START_DATETIME) END) AS CT_HOURS_STROKE,
    MIN(r.RAB_REQUEST_DATETIME) AS Earliest_Rad_Order_DateTime, MAX(r.RAB_REQUEST_DATETIME) AS Latest_Rad_Order_DateTime
  FROM NMR.ARCUSAIR.RADIOLOGY r
  LEFT JOIN NMR.ARCUSAIR.EMERGENCY arc_em ON r.RAB_ORDER_ID=arc_em.RAD_ORDER AND r.FACILITYID=arc_em.FACILITYID AND r.MRN=arc_em.MRN
  GROUP BY r.RAB_ORDER_ID, r.FACILITYID, r.MRN
),
ARC_PHARM AS (
  SELECT PRESCRIPTION_ID, FACILITYID AS ARC_FACILITYID, MRN,
    COUNT(DISTINCT NHIC_MEDICATION_CODE) AS C_PHARM_ORDERS,
    COUNT(DISTINCT CASE WHEN DISPENSE_DATE_TIME IS NOT NULL THEN NHIC_MEDICATION_CODE END) AS C_PHARM_ORDERS_COMPLETED,
    MIN(PRESCRIPTION_DATETIME) AS Earliest_Phar_Order_DateTime, MAX(PRESCRIPTION_DATETIME) AS Latest_Phar_Order_DateTime,
    NULL AS Phar_Administr_DateTime
  FROM NMR.ARCUSAIR.PHARMACY GROUP BY PRESCRIPTION_ID, FACILITYID, MRN
),
ARC_PT AS (
  SELECT MRN, FACILITYID AS ARC_FACILITYID, DATEOFBIRTH AS DATE_OF_BIRTH,
    GENDER, MARITALSTATUS AS MARITAL_STATUS, NATIONALITY, RELIGION
  FROM NMR.ARCUSAIR.PATIENT_PROFILE WHERE FACILITYID IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (PARTITION BY FACILITYID, MRN ORDER BY FETCH_TIMESTAMP DESC)=1
),
/* ══ OASIS ════════════════════════════════════════════════════════ */
OASIS_BASE AS (
  SELECT * FROM NMR.OASIS.EMERGENCY
  WHERE CAST(VISIT_DATE_TIME AS DATE) >= {df}{ub_oasis} AND TRIAGE_LEVEL IS NOT NULL
),
OASIS_FINAL AS (
  SELECT t.NHIC_CODE,t.ENCOUNTER_NUMBER,t.MRN,t.VISIT_DATE_TIME,t.ARRIVAL_METHOD,t.REASON_FOR_VISIT,
    t.TRIAGE_LEVEL_CODE,t.TRIAGE_LEVEL,t.TRIAGE_DATETIME,t.ASSIGMENT_DATE_TIME,
    t.PRINCIPAL_DIAGNOSIS,t.SECONDARY_DIAGNOSIS,t.REQUIRED_ADMIT_DATE,
    t.ADMIT_LOCATION,t.DISCHARGE_DISPOSITION,t.DISCHARGE_DATE_TIME,t.FETCH_TIMESTAMP
  FROM (SELECT eb.*, ROW_NUMBER() OVER (PARTITION BY eb.NHIC_CODE,eb.ENCOUNTER_NUMBER,eb.MRN ORDER BY eb.VISIT_DATE_TIME DESC,eb.TRIAGE_DATETIME DESC) AS rn FROM OASIS_BASE eb) t
  WHERE t.rn=1
),
OASIS_ARRIVAL AS (
  SELECT NHIC_CODE,ENCOUNTER_NUMBER,MRN,MIN(VISIT_DATE_TIME) AS ARRIVAL_DATETIME
  FROM OASIS_BASE GROUP BY NHIC_CODE,ENCOUNTER_NUMBER,MRN
),
OASIS_LAB AS (
  WITH OASIS_LAB_KEYS AS (SELECT DISTINCT eb.NHIC_CODE,eb.ENCOUNTER_NUMBER,eb.MRN,eb.LAB_ORDER_ID FROM OASIS_BASE eb WHERE eb.LAB_ORDER_ID IS NOT NULL)
  SELECT k.NHIC_CODE,k.ENCOUNTER_NUMBER,k.MRN,
    SUM(CASE WHEN UPPER(TRIM(l.LAB_ORDER_PRIORITY))='ROUTINE' THEN 1 ELSE 0 END) AS LAB_ORDERS_ROUTINE,
    SUM(CASE WHEN UPPER(TRIM(l.LAB_ORDER_PRIORITY)) IN ('URGENT','ASAP','STATE','ER','STAT') THEN 1 ELSE 0 END) AS LAB_ORDERS_STAT,
    AVG(CASE WHEN UPPER(TRIM(l.LAB_ORDER_PRIORITY))='ROUTINE' THEN DATEDIFF('hour',l.LAB_ORDER_DATE_TIME,l.RESULT_DATE_TIME) END) AS ROUTINE_LAB_TAT_hours,
    AVG(CASE WHEN UPPER(TRIM(l.LAB_ORDER_PRIORITY)) IN ('URGENT','ASAP','STATE','ER','STAT') THEN DATEDIFF('hour',l.LAB_ORDER_DATE_TIME,l.RESULT_DATE_TIME) END) AS STAT_LAB_TAT_hours,
    MIN(l.LAB_ORDER_DATE_TIME) AS Earliest_Lab_Order_DateTime, MAX(l.LAB_ORDER_DATE_TIME) AS Latest_Lab_Order_DateTime,
    AVG(CASE WHEN UPPER(TRIM(l.LAB_ORDER_PRIORITY)) IN ('URGENT','ASAP','STATE','ER','STAT') THEN DATEDIFF('hour',l.RECEIVING_DATE_TIME,l.RESULT_DATE_TIME) END) AS STAT_LAB_TAT_hours_UCC
  FROM OASIS_LAB_KEYS k JOIN NMR.OASIS.LAB l ON k.NHIC_CODE=l.NHIC_CODE AND k.LAB_ORDER_ID=l.LAB_ORDER_ID
  GROUP BY k.NHIC_CODE,k.ENCOUNTER_NUMBER,k.MRN
),
OASIS_RAD AS (
  WITH OASIS_RAD_KEYS AS (SELECT DISTINCT eb.NHIC_CODE,eb.ENCOUNTER_NUMBER,eb.MRN,eb.RAD_ORDER_ID FROM OASIS_BASE eb WHERE eb.RAD_ORDER_ID IS NOT NULL)
  SELECT k.NHIC_CODE,k.ENCOUNTER_NUMBER,k.MRN,
    SUM(CASE WHEN UPPER(TRIM(r.REFERRAL_ORDER_PRIORITY))='ROUTINE' THEN 1 ELSE 0 END) AS RAD_ORDERS_ROUTINE,
    SUM(CASE WHEN UPPER(TRIM(r.REFERRAL_ORDER_PRIORITY)) IN ('URGENT','ASAP','STATE','ER','STAT') THEN 1 ELSE 0 END) AS RAD_ORDERS_STAT,
    AVG(CASE WHEN UPPER(TRIM(r.REFERRAL_ORDER_PRIORITY))='ROUTINE' THEN DATEDIFF('hour',a.ARRIVAL_DATETIME,r.RAD_REPORT_DATETIME) END) AS ROUTINE_RAD_TAT_hours,
    AVG(CASE WHEN UPPER(TRIM(r.REFERRAL_ORDER_PRIORITY)) IN ('URGENT','ASAP','STATE','ER','STAT') THEN DATEDIFF('hour',a.ARRIVAL_DATETIME,r.RAD_REPORT_DATETIME) END) AS STAT_RAD_TAT_hours,
    AVG(CASE WHEN UPPER(TRIM(r.REFERRAL_ORDER_PRIORITY)) IN ('URGENT','ASAP','STATE','ER','STAT') THEN DATEDIFF('hour',r.EXAMINATION_START_DATETIME,r.RAD_REPORT_DATETIME) END) AS STAT_RAD_TAT_hours_UCC,
    SUM(CASE WHEN r.REQUESTED_RAD_SERVICE ILIKE '%CT%' THEN 1 ELSE 0 END) AS CT_ORDERS,
    SUM(CASE WHEN r.REQUESTED_RAD_SERVICE IN ('3035006020','03035006021','03030011855','03035005701','03035005702','03035005703','03035005495','03035006004','03035006031') THEN 1 ELSE 0 END) AS CT_ORDERS_STROKE,
    AVG(CASE WHEN r.REQUESTED_RAD_SERVICE ILIKE '%CT%' THEN DATEDIFF('second',a.ARRIVAL_DATETIME,r.EXAMINATION_START_DATETIME)/3600.0 END) AS CT_START_TIME_hours,
    AVG(CASE WHEN r.REQUESTED_RAD_SERVICE IN ('3035006020','03035006021','03030011855','03035005701','03035005702','03035005703','03035005495','03035006004','03035006031') THEN DATEDIFF('hour',a.ARRIVAL_DATETIME,r.EXAMINATION_START_DATETIME) END) AS CT_HOURS_STROKE,
    MIN(r.REQUEST_DATETIME) AS Earliest_Rad_Order_DateTime, MAX(r.REQUEST_DATETIME) AS Latest_Rad_Order_DateTime
  FROM OASIS_RAD_KEYS k
  JOIN NMR.OASIS.RADIOLOGY r ON k.NHIC_CODE=r.NHIC_CODE AND k.RAD_ORDER_ID=r.RAD_ORDER_ID
  JOIN OASIS_ARRIVAL a ON a.NHIC_CODE=k.NHIC_CODE AND a.ENCOUNTER_NUMBER=k.ENCOUNTER_NUMBER AND a.MRN=k.MRN
  GROUP BY k.NHIC_CODE,k.ENCOUNTER_NUMBER,k.MRN
),
OASIS_PHARM AS (
  WITH OASIS_RX_KEYS AS (SELECT DISTINCT eb.NHIC_CODE,eb.ENCOUNTER_NUMBER,eb.MRN,eb.PRESCRIPTION_ID FROM OASIS_BASE eb WHERE eb.PRESCRIPTION_ID IS NOT NULL)
  SELECT k.NHIC_CODE,k.ENCOUNTER_NUMBER,k.MRN,
    COUNT(p.PRESCRIPTION_ID) AS C_PHARM_ORDERS, COUNT(p.DISPENSE_DATETIME) AS C_PHARM_ORDERS_COMPLETED,
    MIN(p.PRESCRIPTION_DATETIME) AS Earliest_Phar_Order_DateTime, MAX(p.PRESCRIPTION_DATETIME) AS Latest_Phar_Order_DateTime,
    MAX(p.DISPENSE_DATETIME) AS Phar_Administr_DateTime
  FROM OASIS_RX_KEYS k JOIN NMR.OASIS.PHARMACY p ON k.NHIC_CODE=p.NHIC_CODE AND k.PRESCRIPTION_ID=p.PRESCRIPTION_ID
  GROUP BY k.NHIC_CODE,k.ENCOUNTER_NUMBER,k.MRN
),
OASIS_PT AS (
  SELECT DISTINCT pp.MRN,pp.NHIC_CODE,pp.DATE_OF_BIRTH,pp.GENDER,pp.MARITAL_STATUS,pp.NATIONALITY,pp.RELIGION
  FROM NMR.OASIS.PATIENT_PROFILE pp WHERE pp.NHIC_CODE IS NOT NULL
),
/* ══ VIDAPLUS ══════════════════════════════════════════════════════ */
VP_BASE AS (
  SELECT em.FACILITY_NHIC_CODE,em.ENCOUNTER_NO,em.MRN,em.LAB_ORDER_IDS,em.RAD_ORDER_IDS,em.PRESCRIPTION_IDS,
    em.PATIENT_VISIT_DATE_TIME AS PATIENT_VISIT_DATETIME, em.ARRIVAL_METHOD,
    NULL AS REASON_FOR_VISIT, NULL AS TRIAGE_LEVEL_CODE, em.TRIAGE_LEVEL AS TRIAGE_LEVEL_DESC,
    em.TRIAGE_DATE_TIME AS TRIAGE_DATETIME, em.Examination_Date AS PHYSICIAN_ASSIGNMENT_DATETIME,
    em.PRINCIPLE_DIAGNOSIS AS PRINICIPAL_DIAGNOSIS, em.SECONDARY_DIAGNOSIS,
    em.DECISION_TO_DISCHARGE_DATE_TIME AS DECISION_DATETIME,
    CAST(em.ADMIT_LOCATION AS STRING) AS ADMIT_LOCATION, em.discharge_status AS DISCHARGE_DESTINATION,
    em.DISCHARGE_DATE_TIME AS DISCHARGE_DATETIME, em.FETCH_TIMESTAMP
  FROM NMR.VIDAPLUS.EMERGENCY em WHERE CAST(em.PATIENT_VISIT_DATE_TIME AS DATE) >= {df}{ub_visit}
),
VP_LAB_IDS AS (
  SELECT DISTINCT b.FACILITY_NHIC_CODE,b.ENCOUNTER_NO,b.MRN,TRIM(value::STRING) AS LAB_ORDER_ID
  FROM VP_BASE b, LATERAL FLATTEN(INPUT=>SPLIT(REGEXP_REPLACE(NVL(b.LAB_ORDER_IDS,''),'\\s+',''),','))
  WHERE value IS NOT NULL AND TRIM(value::STRING) NOT IN ('','NULL')
),
VP_RAD_IDS AS (
  SELECT DISTINCT b.FACILITY_NHIC_CODE,b.ENCOUNTER_NO,b.MRN,TRIM(value::STRING) AS RAD_ORDER_ID
  FROM VP_BASE b, LATERAL FLATTEN(INPUT=>SPLIT(REGEXP_REPLACE(NVL(b.RAD_ORDER_IDS,''),'\\s+',''),','))
  WHERE value IS NOT NULL AND TRIM(value::STRING) NOT IN ('','NULL')
),
VP_RX_IDS AS (
  SELECT DISTINCT b.FACILITY_NHIC_CODE,b.ENCOUNTER_NO,b.MRN,TRIM(value::STRING) AS PRESCRIPTION_ORDER_ID
  FROM VP_BASE b, LATERAL FLATTEN(INPUT=>SPLIT(REGEXP_REPLACE(NVL(b.PRESCRIPTION_IDS,''),'\\s+',''),','))
  WHERE value IS NOT NULL AND TRIM(value::STRING) NOT IN ('','NULL')
),
VP_LAB_PER_ORDER AS (
  SELECT LAB_ORDER_ID,FACILITY_NHIC_CODE,
    SUM(CASE WHEN LAB_ORDER_PRIORITY='routine' THEN 1 ELSE 0 END) AS LAB_ORDERS_ROUTINE,
    SUM(CASE WHEN LAB_ORDER_PRIORITY IN ('urgent','stat') THEN 1 ELSE 0 END) AS LAB_ORDERS_STAT,
    AVG(CASE WHEN LAB_ORDER_PRIORITY='routine' THEN DATEDIFF('hour',LAB_ORDER_REQUESTED_DATE_TIME,RESULTED_DATE_TIME) END) AS ROUTINE_LAB_TAT_hours,
    AVG(CASE WHEN LAB_ORDER_PRIORITY IN ('urgent','stat') THEN DATEDIFF('hour',LAB_ORDER_REQUESTED_DATE_TIME,RESULTED_DATE_TIME) END) AS STAT_LAB_TAT_hours,
    MIN(LAB_ORDER_REQUESTED_DATE_TIME) AS Earliest_Lab_Order_DateTime, MAX(LAB_ORDER_REQUESTED_DATE_TIME) AS Latest_Lab_Order_DateTime,
    AVG(CASE WHEN LAB_ORDER_PRIORITY IN ('urgent','stat') THEN DATEDIFF('hour',SAMPLE_RECEIVING_DATE_TIME,RESULTED_DATE_TIME) END) AS STAT_LAB_TAT_hours_UCC
  FROM NMR.VIDAPLUS.LAB GROUP BY LAB_ORDER_ID,FACILITY_NHIC_CODE
),
VP_RAD_PER_ORDER AS (
  SELECT RAD_ORDER_ID,FACILITY_NHIC_CODE,
    SUM(CASE WHEN REFERRAL_ORDER_PRIORITY='routine' THEN 1 ELSE 0 END) AS RAD_ORDERS_ROUTINE,
    SUM(CASE WHEN REFERRAL_ORDER_PRIORITY IN ('urgent','stat') THEN 1 ELSE 0 END) AS RAD_ORDERS_STAT,
    AVG(CASE WHEN REFERRAL_ORDER_PRIORITY='routine' THEN DATEDIFF('hour',REQUESTED_DATE_TIME,RAD_REPORT_DATE_TIME) END) AS ROUTINE_RAD_TAT_hours,
    AVG(CASE WHEN REFERRAL_ORDER_PRIORITY IN ('urgent','stat') THEN DATEDIFF('hour',REQUESTED_DATE_TIME,RAD_REPORT_DATE_TIME) END) AS STAT_RAD_TAT_hours,
    AVG(CASE WHEN REFERRAL_ORDER_PRIORITY IN ('urgent','stat') THEN DATEDIFF('hour',EXAMINATION_START_DATE_TIME,RAD_REPORT_DATE_TIME) END) AS STAT_RAD_TAT_hours_UCC,
    MIN(REQUESTED_DATE_TIME) AS Earliest_Rad_Order_DateTime, MAX(REQUESTED_DATE_TIME) AS Latest_Rad_Order_DateTime
  FROM NMR.VIDAPLUS.RADIOLOGY GROUP BY RAD_ORDER_ID,FACILITY_NHIC_CODE
),
VP_CT_PER_ENC AS (
  SELECT e.FACILITY_NHIC_CODE,e.ENCOUNTER_NO,e.MRN,
    SUM(CASE WHEN r.REQUESTED_RAD_SERVICE ILIKE '%CT%' THEN 1 ELSE 0 END) AS CT_ORDERS,
    SUM(CASE WHEN r.RAD_ORDER_TEST_CODE IN ('3035006020','03035006021','03030011855','03035005701','03035005702','03035005703','03035005495','03035006004','03035006031') THEN 1 ELSE 0 END) AS CT_ORDERS_STROKE,
    AVG(CASE WHEN r.REQUESTED_RAD_SERVICE ILIKE '%CT%' THEN DATEDIFF('hour',b.PATIENT_VISIT_DATETIME,r.EXAMINATION_START_DATE_TIME) END) AS CT_START_TIME_hours,
    AVG(CASE WHEN r.RAD_ORDER_TEST_CODE IN ('3035006020','03035006021','03030011855','03035005701','03035005702','03035005703','03035005495','03035006004','03035006031') THEN DATEDIFF('hour',b.PATIENT_VISIT_DATETIME,r.EXAMINATION_START_DATE_TIME) END) AS CT_HOURS_STROKE
  FROM VP_RAD_IDS e JOIN NMR.VIDAPLUS.RADIOLOGY r ON e.RAD_ORDER_ID=r.RAD_ORDER_ID
  JOIN VP_BASE b ON b.FACILITY_NHIC_CODE=e.FACILITY_NHIC_CODE AND b.ENCOUNTER_NO=e.ENCOUNTER_NO AND b.MRN=e.MRN
  GROUP BY e.FACILITY_NHIC_CODE,e.ENCOUNTER_NO,e.MRN
),
VP_RX_PER_ORDER AS (
  SELECT PRESCRIPTION_ORDER_ID,FACILITY_NHIC_CODE,
    COUNT(PRESCRIPTION_ORDER_ID) AS C_PHARM_ORDERS, COUNT(DISPENSE_DATE_TIME) AS C_PHARM_ORDERS_COMPLETED,
    MIN(PHYSICIAN_ORDER_DATE_TIME) AS Earliest_Phar_Order_DateTime, MAX(PHYSICIAN_ORDER_DATE_TIME) AS Latest_Phar_Order_DateTime,
    MAX(Administered_Date_Time) AS Phar_Administr_DateTime
  FROM NMR.VIDAPLUS.PHARMACY GROUP BY PRESCRIPTION_ORDER_ID,FACILITY_NHIC_CODE
),
VP_LAB_AGG AS (
  SELECT e.FACILITY_NHIC_CODE,e.ENCOUNTER_NO,e.MRN,
    SUM(COALESCE(l.LAB_ORDERS_ROUTINE,0)) AS LAB_ORDERS_ROUTINE, AVG(l.ROUTINE_LAB_TAT_hours) AS ROUTINE_LAB_TAT_hours,
    SUM(COALESCE(l.LAB_ORDERS_STAT,0)) AS LAB_ORDERS_STAT, AVG(l.STAT_LAB_TAT_hours) AS STAT_LAB_TAT_hours,
    MIN(l.Earliest_Lab_Order_DateTime) AS Earliest_Lab_Order_DateTime, MAX(l.Latest_Lab_Order_DateTime) AS Latest_Lab_Order_DateTime,
    AVG(l.STAT_LAB_TAT_hours_UCC) AS STAT_LAB_TAT_hours_UCC
  FROM VP_LAB_IDS e LEFT JOIN VP_LAB_PER_ORDER l ON e.LAB_ORDER_ID=l.LAB_ORDER_ID AND e.FACILITY_NHIC_CODE=l.FACILITY_NHIC_CODE
  GROUP BY e.FACILITY_NHIC_CODE,e.ENCOUNTER_NO,e.MRN
),
VP_RAD_AGG AS (
  SELECT e.FACILITY_NHIC_CODE,e.ENCOUNTER_NO,e.MRN,
    SUM(COALESCE(r.RAD_ORDERS_ROUTINE,0)) AS RAD_ORDERS_ROUTINE, AVG(r.ROUTINE_RAD_TAT_hours) AS ROUTINE_RAD_TAT_hours,
    SUM(COALESCE(r.RAD_ORDERS_STAT,0)) AS RAD_ORDERS_STAT, AVG(r.STAT_RAD_TAT_hours) AS STAT_RAD_TAT_hours,
    AVG(r.STAT_RAD_TAT_hours_UCC) AS STAT_RAD_TAT_hours_UCC,
    MAX(ct.CT_ORDERS) AS CT_ORDERS, MAX(ct.CT_START_TIME_hours) AS CT_START_TIME_hours,
    MAX(ct.CT_ORDERS_STROKE) AS CT_ORDERS_STROKE, AVG(ct.CT_HOURS_STROKE) AS CT_HOURS_STROKE,
    MIN(r.Earliest_Rad_Order_DateTime) AS Earliest_Rad_Order_DateTime, MAX(r.Latest_Rad_Order_DateTime) AS Latest_Rad_Order_DateTime
  FROM VP_RAD_IDS e
  LEFT JOIN VP_RAD_PER_ORDER r ON e.RAD_ORDER_ID=r.RAD_ORDER_ID AND e.FACILITY_NHIC_CODE=r.FACILITY_NHIC_CODE
  LEFT JOIN VP_CT_PER_ENC ct ON ct.FACILITY_NHIC_CODE=e.FACILITY_NHIC_CODE AND ct.ENCOUNTER_NO=e.ENCOUNTER_NO AND ct.MRN=e.MRN
  GROUP BY e.FACILITY_NHIC_CODE,e.ENCOUNTER_NO,e.MRN
),
VP_RX_AGG AS (
  SELECT e.FACILITY_NHIC_CODE,e.ENCOUNTER_NO,e.MRN,
    SUM(COALESCE(x.C_PHARM_ORDERS,0)) AS C_PHARM_ORDERS, SUM(COALESCE(x.C_PHARM_ORDERS_COMPLETED,0)) AS C_PHARM_ORDERS_COMPLETED,
    MIN(x.Earliest_Phar_Order_DateTime) AS Earliest_Phar_Order_DateTime, MAX(x.Latest_Phar_Order_DateTime) AS Latest_Phar_Order_DateTime,
    MAX(x.Phar_Administr_DateTime) AS Phar_Administr_DateTime
  FROM VP_RX_IDS e LEFT JOIN VP_RX_PER_ORDER x ON e.PRESCRIPTION_ORDER_ID=x.PRESCRIPTION_ORDER_ID AND e.FACILITY_NHIC_CODE=x.FACILITY_NHIC_CODE
  GROUP BY e.FACILITY_NHIC_CODE,e.ENCOUNTER_NO,e.MRN
),
VP_PT AS (
  SELECT DISTINCT MRN,FACILITY_NHIC_CODE,DATE_OF_BIRTH,PATIENT_GENDER AS GENDER,MARITAL_STATUS,NATIONALITY,RELIGION
  FROM NMR.VIDAPLUS.PATIENT_PROFILE WHERE FACILITY_NHIC_CODE IS NOT NULL
),
/* ══ VIDA ═════════════════════════════════════════════════════════ */
VIDA_BASE AS (
  SELECT em."FACILITY_CODE(NHIC)" AS VIDA_FAC, em.ENCOUNTER_NUMBER, CAST(em.MRN AS STRING) AS MRN,
    em.LAB_ORDER_IDS, em.RAD_ORDER_IDS, em.PRESCRIPTION_ORDER_ID AS PRESCRIPTION_IDS,
    em.PATIENT_VISIT_DATE_TIME AS PATIENT_VISIT_DATETIME, CAST(em.ARRIVAL_METHOD AS STRING) AS ARRIVAL_METHOD,
    CAST(NULL AS STRING) AS REASON_FOR_VISIT, CAST(NULL AS STRING) AS TRIAGE_LEVEL_CODE,
    CAST(em.TRIAGE_LEVEL AS STRING) AS TRIAGE_LEVEL_DESC, em.TRIAGE_DATE AS TRIAGE_DATETIME,
    em.PHYSICIAN_ASSIGNMENT_DATE_TIME AS PHYSICIAN_ASSIGNMENT_DATETIME,
    em.PRINCIPAL_DIAGNOSIS AS PRINICIPAL_DIAGNOSIS, em.SECONDARY_DIAGNOSIS,
    CASE WHEN em.WARD_NAME IN ('ICU','Male ward','Female ward') THEN em.ADMITTED_DATE_TIME
         ELSE em.DECISION_TO_DISCHARGE_DATE_TIME END AS DECISION_DATETIME,
    CAST(NULL AS STRING) AS ADMIT_LOCATION, CAST(em.WARD_NAME AS STRING) AS DISCHARGE_DESTINATION,
    em.DISCHARGE_DATE_TIME AS DISCHARGE_DATETIME, em.FETCH_TIMESTAMP
  FROM NMR.VIDA.EMERGENCY em WHERE CAST(em.PATIENT_VISIT_DATE_TIME AS DATE) >= {df}{ub_visit}
),
VIDA_LAB_IDS AS (
  SELECT DISTINCT b.VIDA_FAC,b.ENCOUNTER_NUMBER,b.MRN,TRIM(value::STRING) AS LAB_ORDER_ID
  FROM VIDA_BASE b, LATERAL FLATTEN(INPUT=>SPLIT(REGEXP_REPLACE(NVL(b.LAB_ORDER_IDS,''),'\\s+',''),','))
  WHERE value IS NOT NULL AND TRIM(value::STRING) NOT IN ('','NULL')
),
VIDA_RAD_IDS AS (
  SELECT DISTINCT b.VIDA_FAC,b.ENCOUNTER_NUMBER,b.MRN,TRIM(value::STRING) AS RAD_ORDER_ID
  FROM VIDA_BASE b, LATERAL FLATTEN(INPUT=>SPLIT(REGEXP_REPLACE(NVL(b.RAD_ORDER_IDS,''),'\\s+',''),','))
  WHERE value IS NOT NULL AND TRIM(value::STRING) NOT IN ('','NULL')
),
VIDA_RX_IDS AS (
  SELECT DISTINCT b.VIDA_FAC,b.ENCOUNTER_NUMBER,b.MRN,TRIM(value::STRING) AS PRESCRIPTION_ORDER_ID
  FROM VIDA_BASE b, LATERAL FLATTEN(INPUT=>SPLIT(REGEXP_REPLACE(NVL(b.PRESCRIPTION_IDS,''),'\\s+',''),','))
  WHERE value IS NOT NULL AND TRIM(value::STRING) NOT IN ('','NULL')
),
VIDA_LAB_AGG AS (
  SELECT e.VIDA_FAC,e.ENCOUNTER_NUMBER,e.MRN,
    SUM(COALESCE(l.LAB_ORDERS_ROUTINE,0)) AS LAB_ORDERS_ROUTINE, AVG(l.ROUTINE_LAB_TAT_hours) AS ROUTINE_LAB_TAT_hours,
    SUM(COALESCE(l.LAB_ORDERS_STAT,0)) AS LAB_ORDERS_STAT, AVG(l.STAT_LAB_TAT_hours) AS STAT_LAB_TAT_hours,
    MIN(l.Earliest_Lab_Order_DateTime) AS Earliest_Lab_Order_DateTime, MAX(l.Latest_Lab_Order_DateTime) AS Latest_Lab_Order_DateTime,
    AVG(l.STAT_LAB_TAT_hours_UCC) AS STAT_LAB_TAT_hours_UCC
  FROM VIDA_LAB_IDS e
  LEFT JOIN (SELECT LAB_ORDER_ID,"FACILITY_CODE(NHIC)" AS VIDA_FAC,ENCOUNTER_NUMBER,MRN,
    COUNT(DISTINCT CASE WHEN UPPER(TRIM(LAB_ORDER_PRIORITY)) IN ('Routine') THEN LAB_ORDER_ID END) AS LAB_ORDERS_ROUTINE,
    COUNT(DISTINCT CASE WHEN UPPER(TRIM(LAB_ORDER_PRIORITY)) IN ('STAT','URGENT') THEN LAB_ORDER_ID END) AS LAB_ORDERS_STAT,
    AVG(CASE WHEN LAB_ORDER_PRIORITY='Routine' THEN DATEDIFF('hour',PHYSICIAN_LAB_ORDER_DATE_TIME,RESULT_DATE_TIME) END) AS ROUTINE_LAB_TAT_hours,
    AVG(CASE WHEN LAB_ORDER_PRIORITY IN ('Urgent','stat') THEN DATEDIFF('hour',PHYSICIAN_LAB_ORDER_DATE_TIME,RESULT_DATE_TIME) END) AS STAT_LAB_TAT_hours,
    MIN(PHYSICIAN_LAB_ORDER_DATE_TIME) AS Earliest_Lab_Order_DateTime, MAX(PHYSICIAN_LAB_ORDER_DATE_TIME) AS Latest_Lab_Order_DateTime,
    AVG(CASE WHEN LAB_ORDER_PRIORITY IN ('Urgent','stat') THEN DATEDIFF('hour',RECEIVING_DATE_TIME,RESULT_DATE_TIME) END) AS STAT_LAB_TAT_hours_UCC
    FROM NMR.VIDA.LAB GROUP BY LAB_ORDER_ID,"FACILITY_CODE(NHIC)",ENCOUNTER_NUMBER,MRN) l
  ON e.ENCOUNTER_NUMBER=l.ENCOUNTER_NUMBER AND e.VIDA_FAC=l.VIDA_FAC AND e.MRN=l.MRN
  GROUP BY e.VIDA_FAC,e.ENCOUNTER_NUMBER,e.MRN
),
VIDA_RAD_AGG AS (
  SELECT e.VIDA_FAC,e.ENCOUNTER_NUMBER,e.MRN,
    SUM(COALESCE(r.RAD_ORDERS_ROUTINE,0)) AS RAD_ORDERS_ROUTINE, AVG(r.ROUTINE_RAD_TAT_hours) AS ROUTINE_RAD_TAT_hours,
    SUM(COALESCE(r.RAD_ORDERS_STAT,0)) AS RAD_ORDERS_STAT, AVG(r.STAT_RAD_TAT_hours) AS STAT_RAD_TAT_hours,
    AVG(r.STAT_RAD_TAT_hours_UCC) AS STAT_RAD_TAT_hours_UCC,
    MAX(ct.CT_ORDERS) AS CT_ORDERS, MAX(ct.CT_START_TIME_hours) AS CT_START_TIME_hours,
    MAX(ct.CT_ORDERS_STROKE) AS CT_ORDERS_STROKE, AVG(ct.CT_HOURS_STROKE) AS CT_HOURS_STROKE,
    MIN(ct.Earliest_Rad_Order_DateTime) AS Earliest_Rad_Order_DateTime, MAX(ct.Latest_Rad_Order_DateTime) AS Latest_Rad_Order_DateTime
  FROM VIDA_RAD_IDS e
  LEFT JOIN (SELECT RAD_ORDER_ID,"FACILITY_CODE(NHIC)" AS VIDA_FAC,ENCOUNTER_NUMBER,MRN,
    COUNT(DISTINCT CASE WHEN RAD_ORDER_PRIORITY='Routine' THEN RAD_ORDER_ID END) AS RAD_ORDERS_ROUTINE,
    COUNT(DISTINCT CASE WHEN RAD_ORDER_PRIORITY IN ('Others','Urgent') THEN RAD_ORDER_ID END) AS RAD_ORDERS_STAT,
    AVG(CASE WHEN RAD_ORDER_PRIORITY='Routine' THEN DATEDIFF('hour',REQUEST_DATE_TIME,RAD_REPORT_DATE_TIME) END) AS ROUTINE_RAD_TAT_hours,
    AVG(CASE WHEN RAD_ORDER_PRIORITY IN ('Urgent','Others') THEN DATEDIFF('hour',REQUEST_DATE_TIME,RAD_REPORT_DATE_TIME) END) AS STAT_RAD_TAT_hours,
    AVG(CASE WHEN RAD_ORDER_PRIORITY IN ('Urgent','Others') THEN DATEDIFF('hour',REQUEST_DATE_TIME,RAD_REPORT_DATE_TIME) END) AS STAT_RAD_TAT_hours_UCC
    FROM NMR.VIDA.RADIOLOGY GROUP BY RAD_ORDER_ID,"FACILITY_CODE(NHIC)",ENCOUNTER_NUMBER,MRN) r
  ON e.ENCOUNTER_NUMBER=r.ENCOUNTER_NUMBER AND e.VIDA_FAC=r.VIDA_FAC AND e.MRN=r.MRN
  LEFT JOIN (SELECT e2.VIDA_FAC,e2.ENCOUNTER_NUMBER,e2.MRN,
    SUM(CASE WHEN r2.REQUESTED_RAD_SERVICE ILIKE '%CT%' THEN 1 ELSE 0 END) AS CT_ORDERS,
    SUM(CASE WHEN r2.RAD_ORDER_TEST_CODE IN ('3035006020','03035006021','03030011855','03035005701','03035005702','03035005703','03035005495','03035006004','03035006031') THEN 1 ELSE 0 END) AS CT_ORDERS_STROKE,
    AVG(CASE WHEN r2.REQUESTED_RAD_SERVICE ILIKE '%CT%' THEN DATEDIFF('hour',b2.PATIENT_VISIT_DATETIME,r2.EXAMINATION_START_DATE_TIME) END) AS CT_START_TIME_hours,
    AVG(CASE WHEN r2.RAD_ORDER_TEST_CODE IN ('3035006020','03035006021','03030011855','03035005701','03035005702','03035005703','03035005495','03035006004','03035006031') THEN DATEDIFF('hour',b2.PATIENT_VISIT_DATETIME,r2.EXAMINATION_START_DATE_TIME) END) AS CT_HOURS_STROKE,
    MIN(r2.REQUEST_DATE_TIME) AS Earliest_Rad_Order_DateTime, MAX(r2.REQUEST_DATE_TIME) AS Latest_Rad_Order_DateTime
    FROM VIDA_RAD_IDS e2 JOIN NMR.VIDA.RADIOLOGY r2 ON e2.RAD_ORDER_ID=r2.RAD_ORDER_ID
    JOIN VIDA_BASE b2 ON b2.VIDA_FAC=e2.VIDA_FAC AND b2.ENCOUNTER_NUMBER=e2.ENCOUNTER_NUMBER AND b2.MRN=e2.MRN
    GROUP BY e2.VIDA_FAC,e2.ENCOUNTER_NUMBER,e2.MRN) ct
  ON ct.VIDA_FAC=e.VIDA_FAC AND ct.ENCOUNTER_NUMBER=e.ENCOUNTER_NUMBER AND ct.MRN=e.MRN
  GROUP BY e.VIDA_FAC,e.ENCOUNTER_NUMBER,e.MRN
),
VIDA_RX_AGG AS (
  SELECT e.VIDA_FAC,e.ENCOUNTER_NUMBER,e.MRN,
    SUM(COALESCE(x.C_PHARM_ORDERS,0)) AS C_PHARM_ORDERS, SUM(COALESCE(x.C_PHARM_ORDERS_COMPLETED,0)) AS C_PHARM_ORDERS_COMPLETED,
    MIN(x.Earliest_Phar_Order_DateTime) AS Earliest_Phar_Order_DateTime, MAX(x.Latest_Phar_Order_DateTime) AS Latest_Phar_Order_DateTime,
    MAX(x.Phar_Administr_DateTime) AS Phar_Administr_DateTime
  FROM VIDA_RX_IDS e
  LEFT JOIN (SELECT PRESCRIPTION_ORDER_ID,"FACILITY_CODE(NHIC)" AS VIDA_FAC,ENCOUNTER_NO,MRN,
    COUNT(PRESCRIPTION_ORDER_ID) AS C_PHARM_ORDERS, COUNT(DISPENSE_DATE_TIME) AS C_PHARM_ORDERS_COMPLETED,
    MIN(PHYSICIAN_ORDER_DATE_TIME) AS Earliest_Phar_Order_DateTime, MAX(PHYSICIAN_ORDER_DATE_TIME) AS Latest_Phar_Order_DateTime,
    MAX(ADMINISTERED_DATE_TIME) AS Phar_Administr_DateTime
    FROM NMR.VIDA.PHARMACY GROUP BY PRESCRIPTION_ORDER_ID,"FACILITY_CODE(NHIC)",ENCOUNTER_NO,MRN) x
  ON e.VIDA_FAC=x.VIDA_FAC AND e.ENCOUNTER_NUMBER=x.ENCOUNTER_NO AND e.MRN=x.MRN
  GROUP BY e.VIDA_FAC,e.ENCOUNTER_NUMBER,e.MRN
),
VIDA_PT AS (
  SELECT DISTINCT ID_NUMBER AS MRN, SHC_CODE AS VIDA_FAC, DATEOFBIRTH AS DATE_OF_BIRTH,
    PATIENT_GENDER AS GENDER, MARITAL_STATUS, NATIONALITY, NULL AS RELIGION
  FROM NMR.VIDA.PATIENT_PROFILE WHERE SHC_CODE IS NOT NULL
),
/* ══ SW_EMERGENCY UNION ════════════════════════════════════════════ */
SW_EMERGENCY AS (
  SELECT CAST(em.FACILILTY_CODE AS STRING) AS FACILITY_CODE_NHIC, CAST(em.ENCOUNTER_NUMBER AS STRING) AS ENCOUNTER_NUMBER, CAST(em.MEDICAL_RECORD_NUMBER_MRN AS STRING) AS MRN,
    em.PATIENT_VISIT_DATE_TIME AS PATIENT_VISIT_DATETIME, em.ARRIVAL_METHOD, em.REASON_FOR_VISIT,
    em.TRIAGE_LEVEL_CODE, em.TRIAGE_LEVEL AS TRIAGE_LEVEL_DESC, em.TRIAGE_DATE_TIME AS TRIAGE_DATETIME,
    em.PHYSICIAN_EXAMINATION_DATE_TIME AS PHYSICIAN_ASSIGNMENT_DATETIME,
    em.PRINICIPAL_DIAGNOSIS, em.SECONDARY_DIAGNOSIS, em.DECISION_DATE_TIME AS DECISION_DATETIME,
    CAST(em.ADMIT_LOCATION AS STRING) AS ADMIT_LOCATION, em.DISCHARGE_DESTINATION, em.DISCHARGE_DATETIME, em.FETCH_TIMESTAMP,
    lb.LAB_ORDERS_ROUTINE, lb.ROUTINE_LAB_TAT_hours, lb.LAB_ORDERS_STAT, lb.STAT_LAB_TAT_hours,
    lb.Earliest_Lab_Order_DateTime, lb.Latest_Lab_Order_DateTime, lb.STAT_LAB_TAT_hours_UCC,
    rd.RAD_ORDERS_ROUTINE, rd.ROUTINE_RAD_TAT_hours, rd.RAD_ORDERS_STAT, rd.STAT_RAD_TAT_hours,
    rd.STAT_RAD_TAT_hours_UCC, rd.CT_ORDERS, rd.CT_START_TIME_hours, rd.CT_ORDERS_STROKE, rd.CT_HOURS_STROKE,
    rd.Earliest_Rad_Order_DateTime, rd.Latest_Rad_Order_DateTime,
    ph.C_PHARM_ORDERS, ph.C_PHARM_ORDERS_COMPLETED, ph.Earliest_Phar_Order_DateTime, ph.Latest_Phar_Order_DateTime, ph.Phar_Administr_DateTime,
    DATEDIFF('year',p.DATE_OF_BIRTH,CAST(em.PATIENT_VISIT_DATE_TIME AS DATE)) AS AGE_YEARS,
    p.GENDER, p.MARITAL_STATUS, p.NATIONALITY, p.RELIGION,
    CASE WHEN CAST(em.FACILILTY_CODE AS STRING) IN ('10000000035152','10000000038131','10000000000539','10000000038130') THEN TRUE
         WHEN em.LOCATION=' Rapid Assessment الفحص السريع (NOJOUD)Clinic' THEN TRUE ELSE FALSE END AS UCC_FLAG,
    'MCC' AS HIS
  FROM NMR.MCC.EMERGENCY em
  LEFT JOIN MCC_LAB   lb ON em.FACILILTY_CODE=lb.FACILILTY_CODE AND em.ENCOUNTER_NUMBER=lb.ENCOUNTER_NUMBER AND em.MEDICAL_RECORD_NUMBER_MRN=lb.MEDICAL_RECORD_NUMBER_MRN
  LEFT JOIN MCC_RAD   rd ON em.FACILILTY_CODE=rd.FACILILTY_CODE AND em.ENCOUNTER_NUMBER=rd.ENCOUNTER_NUMBER AND em.MEDICAL_RECORD_NUMBER_MRN=rd.MEDICAL_RECORD_NUMBER_MRN
  LEFT JOIN MCC_PHARM ph ON em.FACILILTY_CODE=ph.FACILILTY_CODE AND em.ENCOUNTER_NUMBER=ph.ENCOUNTER_NUMBER AND em.MEDICAL_RECORD_NUMBER_MRN=ph.MEDICAL_RECORD_NUMBER_MRN
  LEFT JOIN MCC_PT    p  ON em.FACILILTY_CODE=p.FACILILTY_CODE AND em.MEDICAL_RECORD_NUMBER_MRN=p.MEDICAL_RECORD_NUMBER_MRN
  WHERE CAST(em.PATIENT_VISIT_DATE_TIME AS DATE) >= {df}{ub_visit}

  UNION ALL

  SELECT CAST(em.FACILITY_CODE_NHIC AS STRING), CAST(em.ENCOUNTER_NUMBER AS STRING), CAST(em.MEDICAL_RECORD_NUMBER_MRN AS STRING),
    em.PATIENT_VISIT_DATE, em.ATS_ARRIVAL_METHOD_NAME, em.REASON_FOR_VISIT,
    em.ATS_TRIAGE_LEVEL, em.ATS_TRIAGE_LEVEL_DESC, em.TRIAGE_DATE_TIME, em.PHYSICIAN_ASSIGNMENT_DATE,
    em.PRINICIPAL_DIAGNOSIS, em.SECONDARY_DIAGNOSIS, em.DECISION_TO_ADMIT_DATE,
    CAST(em.ADMIT_LOCATION_ER_AREA AS STRING), em.ATS_ED_DISCH_DISPOSITION_DESC, em.DISCHARGE_DATE, em.FETCH_TIMESTAMP,
    lb.LAB_ORDERS_ROUTINE, lb.ROUTINE_LAB_TAT_hours, lb.LAB_ORDERS_STAT, lb.STAT_LAB_TAT_hours,
    lb.Earliest_Lab_Order_DateTime, lb.Latest_Lab_Order_DateTime, lb.STAT_LAB_TAT_hours_UCC,
    rd.RAD_ORDERS_ROUTINE, rd.ROUTINE_RAD_TAT_hours, rd.RAD_ORDERS_STAT, rd.STAT_RAD_TAT_hours,
    rd.STAT_RAD_TAT_hours_UCC, rd.CT_ORDERS, rd.CT_START_TIME_hours, rd.CT_ORDERS_STROKE, rd.CT_HOURS_STROKE,
    rd.Earliest_Rad_Order_DateTime, rd.Latest_Rad_Order_DateTime,
    ph.C_PHARM_ORDERS, ph.C_PHARM_ORDERS_COMPLETED, ph.Earliest_Phar_Order_DateTime, ph.Latest_Phar_Order_DateTime, ph.Phar_Administr_DateTime,
    DATEDIFF('year',p.DATE_OF_BIRTH,CAST(em.PATIENT_VISIT_DATE AS DATE)),
    p.GENDER, p.MARITAL_STATUS, p.NATIONALITY, p.RELIGION,
    CASE WHEN em.ATS_SECTION_NAME IN ('Urgent Care Clinic','Urgent Care Center 2','Urgent Care Center 1','Urgent Care Center','Gyne Urgent Care') THEN TRUE ELSE FALSE END,
    'CAREWARE'
  FROM NMR.CAREWARE.EMERGENCY em
  LEFT JOIN CW_LAB   lb ON em.LAB_ORDER_ID   =lb.ENCOUNTER_NUMBER
  LEFT JOIN CW_RAD   rd ON em.RAD_ORDER_ID   =rd.ENCOUNTER_NUMBER
  LEFT JOIN CW_PHARM ph ON em.PRESCRIPTION_ID=ph.ENCOUNTER_NUMBER
  LEFT JOIN CW_PT    p  ON em.FACILITY_CODE_NHIC=p.FACILITY_CODE_NHIC AND em.MEDICAL_RECORD_NUMBER_MRN=p.MEDICAL_RECORD_NUMBER_MRN
  WHERE CAST(em.PATIENT_VISIT_DATE AS DATE) >= {df}{ub_visit_d}

  UNION ALL

  SELECT CAST(f.NHIC_CODE AS STRING), CAST(f.ENCOUNTER_NUMBER AS STRING), CAST(f.MRN AS STRING),
    f.VISIT_DATE_TIME, f.ARRIVAL_METHOD, f.REASON_FOR_VISIT,
    f.TRIAGE_LEVEL_CODE, f.TRIAGE_LEVEL AS TRIAGE_LEVEL_DESC, f.TRIAGE_DATETIME, f.ASSIGMENT_DATE_TIME,
    f.PRINCIPAL_DIAGNOSIS, f.SECONDARY_DIAGNOSIS, f.REQUIRED_ADMIT_DATE,
    CAST(f.ADMIT_LOCATION AS STRING), f.DISCHARGE_DISPOSITION, f.DISCHARGE_DATE_TIME, f.FETCH_TIMESTAMP,
    COALESCE(lb.LAB_ORDERS_ROUTINE,0), lb.ROUTINE_LAB_TAT_hours, COALESCE(lb.LAB_ORDERS_STAT,0), lb.STAT_LAB_TAT_hours,
    lb.Earliest_Lab_Order_DateTime, lb.Latest_Lab_Order_DateTime, lb.STAT_LAB_TAT_hours_UCC,
    COALESCE(rd.RAD_ORDERS_ROUTINE,0), rd.ROUTINE_RAD_TAT_hours, COALESCE(rd.RAD_ORDERS_STAT,0), rd.STAT_RAD_TAT_hours,
    rd.STAT_RAD_TAT_hours_UCC, COALESCE(rd.CT_ORDERS,0), rd.CT_START_TIME_hours, COALESCE(rd.CT_ORDERS_STROKE,0), rd.CT_HOURS_STROKE,
    rd.Earliest_Rad_Order_DateTime, rd.Latest_Rad_Order_DateTime,
    COALESCE(ph.C_PHARM_ORDERS,0), COALESCE(ph.C_PHARM_ORDERS_COMPLETED,0),
    ph.Earliest_Phar_Order_DateTime, ph.Latest_Phar_Order_DateTime, ph.Phar_Administr_DateTime,
    DATEDIFF('year',p.DATE_OF_BIRTH,CAST(f.VISIT_DATE_TIME AS DATE)),
    p.GENDER, p.MARITAL_STATUS, p.NATIONALITY, p.RELIGION,
    FALSE, 'OASIS'
  FROM OASIS_FINAL f
  LEFT JOIN OASIS_LAB   lb ON f.NHIC_CODE=lb.NHIC_CODE AND f.MRN=lb.MRN AND f.ENCOUNTER_NUMBER=lb.ENCOUNTER_NUMBER
  LEFT JOIN OASIS_RAD   rd ON f.NHIC_CODE=rd.NHIC_CODE AND f.MRN=rd.MRN AND f.ENCOUNTER_NUMBER=rd.ENCOUNTER_NUMBER
  LEFT JOIN OASIS_PHARM ph ON f.NHIC_CODE=ph.NHIC_CODE AND f.MRN=ph.MRN AND f.ENCOUNTER_NUMBER=ph.ENCOUNTER_NUMBER
  LEFT JOIN OASIS_PT    p  ON f.NHIC_CODE=p.NHIC_CODE AND f.MRN=p.MRN

  UNION ALL

  SELECT CAST(b.FACILITY_NHIC_CODE AS STRING), CAST(b.ENCOUNTER_NO AS STRING), CAST(b.MRN AS STRING),
    b.PATIENT_VISIT_DATETIME, b.ARRIVAL_METHOD, b.REASON_FOR_VISIT,
    b.TRIAGE_LEVEL_CODE, b.TRIAGE_LEVEL_DESC, b.TRIAGE_DATETIME, b.PHYSICIAN_ASSIGNMENT_DATETIME,
    b.PRINICIPAL_DIAGNOSIS, b.SECONDARY_DIAGNOSIS, b.DECISION_DATETIME,
    b.ADMIT_LOCATION, b.DISCHARGE_DESTINATION, b.DISCHARGE_DATETIME, b.FETCH_TIMESTAMP,
    COALESCE(lab.LAB_ORDERS_ROUTINE,0), lab.ROUTINE_LAB_TAT_hours, COALESCE(lab.LAB_ORDERS_STAT,0), lab.STAT_LAB_TAT_hours,
    lab.Earliest_Lab_Order_DateTime, lab.Latest_Lab_Order_DateTime, lab.STAT_LAB_TAT_hours_UCC,
    COALESCE(rad.RAD_ORDERS_ROUTINE,0), rad.ROUTINE_RAD_TAT_hours, COALESCE(rad.RAD_ORDERS_STAT,0), rad.STAT_RAD_TAT_hours,
    rad.STAT_RAD_TAT_hours_UCC, COALESCE(rad.CT_ORDERS,0), rad.CT_START_TIME_hours, COALESCE(rad.CT_ORDERS_STROKE,0), rad.CT_HOURS_STROKE,
    rad.Earliest_Rad_Order_DateTime, rad.Latest_Rad_Order_DateTime,
    COALESCE(rx.C_PHARM_ORDERS,0), COALESCE(rx.C_PHARM_ORDERS_COMPLETED,0),
    rx.Earliest_Phar_Order_DateTime, rx.Latest_Phar_Order_DateTime, rx.Phar_Administr_DateTime,
    DATEDIFF('year',p.DATE_OF_BIRTH,b.PATIENT_VISIT_DATETIME),
    p.GENDER, p.MARITAL_STATUS, p.NATIONALITY, p.RELIGION,
    FALSE, 'VIDAPLUS'
  FROM VP_BASE b
  LEFT JOIN VP_LAB_AGG lab ON b.FACILITY_NHIC_CODE=lab.FACILITY_NHIC_CODE AND b.ENCOUNTER_NO=lab.ENCOUNTER_NO AND b.MRN=lab.MRN
  LEFT JOIN VP_RAD_AGG rad ON b.FACILITY_NHIC_CODE=rad.FACILITY_NHIC_CODE AND b.ENCOUNTER_NO=rad.ENCOUNTER_NO AND b.MRN=rad.MRN
  LEFT JOIN VP_RX_AGG  rx  ON b.FACILITY_NHIC_CODE=rx.FACILITY_NHIC_CODE  AND b.ENCOUNTER_NO=rx.ENCOUNTER_NO  AND b.MRN=rx.MRN
  LEFT JOIN VP_PT      p   ON b.FACILITY_NHIC_CODE=p.FACILITY_NHIC_CODE   AND b.MRN=p.MRN

  UNION ALL

  SELECT CAST(em.FACILITYID AS STRING), CAST(em.ENCOUNTER_NUMBER AS STRING), CAST(em.MRN AS STRING),
    em.VISITDATE, em.ARRIVAL_METHOD, em.REASON_FOR_VISIT,
    RIGHT(em.TRIAGE_LEVEL_CODE,1), em.TRIAGE_LEVEL_NAME, em.TRIAGE_DATETIME, em.PHYSICIAN_ASSIGNED_DATETIME,
    em.PRINICIPAL_DIAGNOSIS, em.SECONDARYDIAGNOSIS, CAST(NULL AS DATE),
    CAST(em.ADMIT_LOCATION AS STRING), em.DISCHARGE_DESTINATION, em.DISCHARGE_DATETIME, em.FETCH_TIMESTAMP,
    lb.LAB_ORDERS_ROUTINE, lb.ROUTINE_LAB_TAT_hours, lb.LAB_ORDERS_STAT, lb.STAT_LAB_TAT_hours,
    lb.Earliest_Lab_Order_DateTime, lb.Latest_Lab_Order_DateTime, lb.STAT_LAB_TAT_hours_UCC,
    rd.RAD_ORDERS_ROUTINE, rd.ROUTINE_RAD_TAT_hours, rd.RAD_ORDERS_STAT, rd.STAT_RAD_TAT_hours,
    rd.STAT_RAD_TAT_hours_UCC, rd.CT_ORDERS, rd.CT_START_TIME_hours, rd.CT_ORDERS_STROKE, rd.CT_HOURS_STROKE,
    rd.Earliest_Rad_Order_DateTime, rd.Latest_Rad_Order_DateTime,
    ph.C_PHARM_ORDERS, ph.C_PHARM_ORDERS_COMPLETED, ph.Earliest_Phar_Order_DateTime, ph.Latest_Phar_Order_DateTime, ph.Phar_Administr_DateTime,
    DATEDIFF('year',p.DATE_OF_BIRTH,CAST(em.VISITDATE AS DATE)),
    p.GENDER, p.MARITAL_STATUS, p.NATIONALITY, p.RELIGION,
    CASE WHEN em.FACILITYID='10000000045714' THEN TRUE
         WHEN em.ADMIT_LOCATION IN ('UCC - Clinic 2','UCC (Alnqrah)','Urgent Care','Urgent Care Clinic','Urgent Care  الرعاية العاجلة') THEN TRUE ELSE FALSE END,
    'ArcusAir'
  FROM NMR.ARCUSAIR.EMERGENCY em
  LEFT JOIN ARC_LAB   lb ON em.FACILITYID=lb.ARC_FACILITYID AND em.LAB_ORDER      =lb.LAB_ORDER_ID    AND em.MRN=lb.MRN
  LEFT JOIN ARC_RAD   rd ON em.FACILITYID=rd.ARC_FACILITYID AND em.RAD_ORDER      =rd.RAB_ORDER_ID    AND em.MRN=rd.MRN
  LEFT JOIN ARC_PHARM ph ON em.FACILITYID=ph.ARC_FACILITYID AND em.MEDICINE_ORDER =ph.PRESCRIPTION_ID AND em.MRN=ph.MRN
  LEFT JOIN ARC_PT    p  ON em.FACILITYID=p.ARC_FACILITYID  AND em.MRN=p.MRN
  WHERE CAST(em.VISITDATE AS DATE) >= {df}{ub_visitd2}

  UNION ALL

  SELECT CAST(b.VIDA_FAC AS STRING), CAST(b.ENCOUNTER_NUMBER AS STRING), CAST(b.MRN AS STRING),
    b.PATIENT_VISIT_DATETIME, b.ARRIVAL_METHOD, b.REASON_FOR_VISIT,
    b.TRIAGE_LEVEL_CODE, b.TRIAGE_LEVEL_DESC, b.TRIAGE_DATETIME, b.PHYSICIAN_ASSIGNMENT_DATETIME,
    b.PRINICIPAL_DIAGNOSIS, b.SECONDARY_DIAGNOSIS, b.DECISION_DATETIME,
    b.ADMIT_LOCATION, b.DISCHARGE_DESTINATION, b.DISCHARGE_DATETIME, b.FETCH_TIMESTAMP,
    COALESCE(lab.LAB_ORDERS_ROUTINE,0), lab.ROUTINE_LAB_TAT_hours, COALESCE(lab.LAB_ORDERS_STAT,0), lab.STAT_LAB_TAT_hours,
    lab.Earliest_Lab_Order_DateTime, lab.Latest_Lab_Order_DateTime, lab.STAT_LAB_TAT_hours_UCC,
    COALESCE(rad.RAD_ORDERS_ROUTINE,0), rad.ROUTINE_RAD_TAT_hours, COALESCE(rad.RAD_ORDERS_STAT,0), rad.STAT_RAD_TAT_hours,
    rad.STAT_RAD_TAT_hours_UCC, COALESCE(rad.CT_ORDERS,0), rad.CT_START_TIME_hours, COALESCE(rad.CT_ORDERS_STROKE,0), rad.CT_HOURS_STROKE,
    rad.Earliest_Rad_Order_DateTime, rad.Latest_Rad_Order_DateTime,
    COALESCE(rx.C_PHARM_ORDERS,0), COALESCE(rx.C_PHARM_ORDERS_COMPLETED,0),
    rx.Earliest_Phar_Order_DateTime, rx.Latest_Phar_Order_DateTime, rx.Phar_Administr_DateTime,
    DATEDIFF('year',p.DATE_OF_BIRTH,b.PATIENT_VISIT_DATETIME),
    p.GENDER, p.MARITAL_STATUS, p.NATIONALITY, p.RELIGION,
    FALSE, 'VIDA'
  FROM VIDA_BASE b
  LEFT JOIN VIDA_LAB_AGG lab ON b.VIDA_FAC=lab.VIDA_FAC AND b.ENCOUNTER_NUMBER=lab.ENCOUNTER_NUMBER AND b.MRN=lab.MRN
  LEFT JOIN VIDA_RAD_AGG rad ON b.VIDA_FAC=rad.VIDA_FAC AND b.ENCOUNTER_NUMBER=rad.ENCOUNTER_NUMBER AND b.MRN=rad.MRN
  LEFT JOIN VIDA_RX_AGG  rx  ON b.VIDA_FAC=rx.VIDA_FAC  AND b.ENCOUNTER_NUMBER=rx.ENCOUNTER_NUMBER  AND b.MRN=rx.MRN
  LEFT JOIN VIDA_PT      p   ON b.VIDA_FAC=p.VIDA_FAC   AND b.MRN=p.MRN

  UNION ALL

  SELECT CAST(em.FACILITY_NHIC AS STRING), CAST(em.ENCOUNTER_NUMBER AS STRING), CAST(em.MRN AS STRING),
    em.VISIT_DATE, em.ARRIVAL_METHOD, em.REASON_FOR_VISIT,
    em.TRIAGE_LEVEL_CODE, em.TRIAGE_LEVEL, em.TRIAGE_DATE, em.PHYSICIAN_ASSIGNEMENT_DATE,
    em.PRINCIPAL_DIAGNOSIS, em.SECONDARY_DIAGNOSIS, em.DECISION_TO_ADMIT_DATE,
    CAST(em.ADMIT_LOCATION AS STRING), em.DISCHARGE_DISPOSITION, em.DISCHARGE_DATE, em.FETCH_TIMESTAMP,
    NULL,NULL,NULL,NULL,NULL,NULL,NULL,
    NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
    NULL,NULL,NULL,NULL,NULL,
    NULL,NULL,NULL,NULL,NULL,
    FALSE,'INTERSYSTEM'
  FROM NMR.INTERSYSTEM.EMERGENCY em WHERE CAST(em.VISIT_DATE AS DATE) >= {df}{ub_visit_i}

  UNION ALL

  SELECT CAST(em.NHIC_CODE AS STRING), CAST(em.ENCOUNTEREPICCSN AS STRING), CAST(em.PRIMARYMRN AS STRING),
    em.ARRIVALINSTANT, NULL, NULL,
    em.CTASLEVEL, em.ACUITYLEVEL, em.TRIAGESTARTINSTANT, em.FirstProviderContactInstant,
    NULL, NULL, em.FirstConsultationOrderingInstant,
    NULL, em.DISCHARGEDISPOSITION, em.DISPOSITIONINSTANT, em.FETCH_TIMESTAMP,
    NULL,NULL,NULL,NULL, em.FIRSTLABORDEREDINSTANT, NULL, NULL,
    NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
    em.FIRSTRADIOLOGYORDERINGINSTANT, NULL,
    NULL,NULL, em.FIRSTMEDICATIONORDERINGINSTANT, NULL, em.FIRSTMEDICATIONADMINISTRATIONINSTANT,
    NULL,NULL,NULL,NULL,NULL,
    FALSE,'EPIC'
  FROM NMR.EPIC.EMERGENCY em WHERE CAST(em.ARRIVALINSTANT AS DATE) >= {df}{ub_arrival}
)"""


# ─────────────────────── KPI definitions ─────────────────────────────────────

KPIS = [
    {"n": 1,  "title": "No. of patients seen in ED",              "formula": "COUNT(DISTINCT encounters)",                                    "type": "Volume",  "group": "rate",  "dax_fix": False, "null_his": False},
    {"n": 2,  "title": "% referred to UCC",                       "formula": "UCC_FLAG=TRUE / Total × 100",                                  "type": "Process", "group": "rate",  "dax_fix": False, "null_his": False},
    {"n": 3,  "title": "Door to physician",                       "formula": "PHYSICIAN_ASSIGNMENT − PATIENT_VISIT (min)",                   "type": "Process", "group": "time",  "dax_fix": False, "null_his": False},
    {"n": 4,  "title": "Physician to order",                      "formula": "Earliest order − PHYSICIAN_ASSIGNMENT (min, excl. CTAS 1&2)", "type": "Process", "group": "time",  "dax_fix": False, "null_his": True},
    {"n": 5,  "title": "Order to medication administration",      "formula": "Phar_Administr − Latest_Phar_Order (min)",                    "type": "Process", "group": "time",  "dax_fix": False, "null_his": True},
    {"n": 6,  "title": "Order to decision",                       "formula": "DECISION − Earliest order (min, excl. CTAS 1&2)",             "type": "Process", "group": "time",  "dax_fix": False, "null_his": True},
    {"n": 7,  "title": "Decision to disposition",                 "formula": "DISCHARGE − DECISION (min)",                                   "type": "Process", "group": "time",  "dax_fix": False, "null_his": False},
    {"n": 8,  "title": "Decision to discharge (home)",            "formula": "DISCHARGE − DECISION where dest=Home (min)",                  "type": "Process", "group": "time",  "dax_fix": False, "null_his": False},
    {"n": 9,  "title": "Decision to admission – ward",            "formula": "DISCHARGE − DECISION where dest=Ward (min)",                  "type": "Process", "group": "time",  "dax_fix": False, "null_his": False},
    {"n": 10, "title": "Decision to admission – ICU",             "formula": "DISCHARGE − DECISION where dest=ICU (min)",                   "type": "Process", "group": "time",  "dax_fix": False, "null_his": False},
    {"n": 11, "title": "% patients disposed within 4 hours",     "formula": "Disposed ≤240 min / Total × 100",                             "type": "Process", "group": "rate",  "dax_fix": False, "null_his": False},
    {"n": 12, "title": "Average ED ALOS (all patients)",          "formula": "COALESCE(DISCHARGE,FETCH_TIMESTAMP) − ARRIVAL (min)",         "type": "Process", "group": "time",  "dax_fix": False, "null_his": False},
    {"n": 13, "title": "ED ALOS – ICU admissions",                "formula": "COALESCE(DISCHARGE,FETCH_TIMESTAMP) − ARRIVAL where ICU",     "type": "Process", "group": "time",  "dax_fix": False, "null_his": False},
    {"n": 14, "title": "ED ALOS – ward admissions",               "formula": "COALESCE(DISCHARGE,FETCH_TIMESTAMP) − ARRIVAL where Ward",    "type": "Process", "group": "time",  "dax_fix": False, "null_his": False},
    {"n": 15, "title": "Average transfer time (EMS)",             "formula": "Patient leaves − EMS notified (min) — pipeline pending",      "type": "Process", "group": "time",  "dax_fix": False, "null_his": True},
    {"n": 16, "title": "Lab TAT – STAT",                          "formula": "SUM(LAB_ORDERS_STAT) + AVG(STAT_LAB_TAT_hours × 60)",         "type": "Process", "group": "time",  "dax_fix": True,  "null_his": True},
    {"n": 17, "title": "Lab TAT – POCT",                          "formula": "SUM(LAB_ORDERS_STAT) + AVG(STAT_LAB_TAT_hours_UCC × 60)",     "type": "Process", "group": "time",  "dax_fix": True,  "null_his": True},
    {"n": 18, "title": "Radiology TAT – STAT",                    "formula": "SUM(RAD_ORDERS_STAT) + AVG(STAT_RAD_TAT_hours × 60)",         "type": "Process", "group": "time",  "dax_fix": True,  "null_his": True},
    {"n": 19, "title": "LAMA rate",                               "formula": "LAMA / Total × 100",                                          "type": "Outcome", "group": "rate",  "dax_fix": False, "null_his": False},
    {"n": 20, "title": "LWBS rate",                               "formula": "LWBS / Total × 100",                                          "type": "Outcome", "group": "rate",  "dax_fix": False, "null_his": False},
    {"n": 21, "title": "Return to ED within 72 hrs",              "formula": "Revisit prev DISCHARGE→curr VISIT ≤72 hrs, same ICD",         "type": "Outcome", "group": "rate",  "dax_fix": False, "null_his": False},
    {"n": 22, "title": "ED mortality rate",                       "formula": "Deceased / Total excl. DOA × 100",                            "type": "Outcome", "group": "rate",  "dax_fix": False, "null_his": False},
    {"n": 23, "title": "Non-urgent ED visit rate (CTAS 4 & 5)",   "formula": "Triage level 4 or 5 / Total × 100",                          "type": "Process", "group": "rate",  "dax_fix": False, "null_his": False},
    {"n": 24, "title": "Door to triage",                          "formula": "TRIAGE_DATETIME − PATIENT_VISIT_DATETIME (min)",               "type": "Process", "group": "time",  "dax_fix": False, "null_his": False},
]

# ─────────────────────── KPI SQL generators ──────────────────────────────────

def kpi_sql(n: int, df: str, dt: str, hf: str, ff: str, g: str) -> str:
    src = src_alias(hf, ff)
    gc  = gran_col(g)
    gg  = gran_grp(g)
    lv  = lambda mn,mx,col: f"DATEDIFF('minute',{col[0]},{col[1]})"

    Q = {
        1: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT e.ENCOUNTER_NUMBER) AS C_Visits\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        2: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT e.ENCOUNTER_NUMBER) AS C_Visits,\n  COUNT(DISTINCT CASE WHEN e.UCC_FLAG=TRUE THEN e.ENCOUNTER_NUMBER END) AS C_UCC,\n  ROUND(COUNT(DISTINCT CASE WHEN e.UCC_FLAG=TRUE THEN e.ENCOUNTER_NUMBER END)*100.0/NULLIF(COUNT(DISTINCT e.ENCOUNTER_NUMBER),0),2) AS Pct_UCC\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        3: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT CASE WHEN e.PHYSICIAN_ASSIGNMENT_DATETIME IS NOT NULL THEN e.ENCOUNTER_NUMBER END) AS C_With_Data,\n  ROUND(AVG(CASE WHEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,e.PHYSICIAN_ASSIGNMENT_DATETIME)>=0 THEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,e.PHYSICIAN_ASSIGNMENT_DATETIME) END),2) AS Avg_Min,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,e.PHYSICIAN_ASSIGNMENT_DATETIME)<20 THEN e.ENCOUNTER_NUMBER END) AS Green_lt20,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,e.PHYSICIAN_ASSIGNMENT_DATETIME) BETWEEN 20 AND 24 THEN e.ENCOUNTER_NUMBER END) AS Amber_20_24,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,e.PHYSICIAN_ASSIGNMENT_DATETIME)>25 THEN e.ENCOUNTER_NUMBER END) AS Red_gt25\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        4: f"/* NOTE: NULL for INTERSYSTEM (no sub-table integration) */\nSELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT CASE WHEN CAST(e.TRIAGE_LEVEL_CODE AS STRING) NOT IN ('1','2') AND LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP))!='9999-01-01'::TIMESTAMP THEN e.ENCOUNTER_NUMBER END) AS C_With_Data,\n  ROUND(AVG(CASE WHEN CAST(e.TRIAGE_LEVEL_CODE AS STRING) NOT IN ('1','2') AND LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP))!='9999-01-01'::TIMESTAMP AND DATEDIFF('minute',e.PHYSICIAN_ASSIGNMENT_DATETIME,LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP)))>=0 THEN DATEDIFF('minute',e.PHYSICIAN_ASSIGNMENT_DATETIME,LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP))) END),2) AS Avg_Physician_to_Order_Min,\n  COUNT(DISTINCT CASE WHEN CAST(e.TRIAGE_LEVEL_CODE AS STRING) NOT IN ('1','2') AND DATEDIFF('minute',e.PHYSICIAN_ASSIGNMENT_DATETIME,LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP)))<10 THEN e.ENCOUNTER_NUMBER END) AS Green_lt10,\n  COUNT(DISTINCT CASE WHEN CAST(e.TRIAGE_LEVEL_CODE AS STRING) NOT IN ('1','2') AND DATEDIFF('minute',e.PHYSICIAN_ASSIGNMENT_DATETIME,LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP))) BETWEEN 10 AND 14 THEN e.ENCOUNTER_NUMBER END) AS Amber_10_14,\n  COUNT(DISTINCT CASE WHEN CAST(e.TRIAGE_LEVEL_CODE AS STRING) NOT IN ('1','2') AND DATEDIFF('minute',e.PHYSICIAN_ASSIGNMENT_DATETIME,LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP)))>15 THEN e.ENCOUNTER_NUMBER END) AS Red_gt15\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        5: f"/* NOTE: Phar_Administr_DateTime NULL for ARCUSAIR; NULL for INTERSYSTEM */\nSELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT CASE WHEN e.Latest_Phar_Order_DateTime IS NOT NULL AND e.Phar_Administr_DateTime IS NOT NULL THEN e.ENCOUNTER_NUMBER END) AS C_With_Data,\n  ROUND(AVG(CASE WHEN e.Latest_Phar_Order_DateTime IS NOT NULL AND e.Phar_Administr_DateTime IS NOT NULL AND DATEDIFF('minute',e.Latest_Phar_Order_DateTime,e.Phar_Administr_DateTime)>=0 THEN DATEDIFF('minute',e.Latest_Phar_Order_DateTime,e.Phar_Administr_DateTime) END),2) AS Avg_Min,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',e.Latest_Phar_Order_DateTime,e.Phar_Administr_DateTime)<30 THEN e.ENCOUNTER_NUMBER END) AS Green_lt30,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',e.Latest_Phar_Order_DateTime,e.Phar_Administr_DateTime) BETWEEN 30 AND 39 THEN e.ENCOUNTER_NUMBER END) AS Amber_30_39,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',e.Latest_Phar_Order_DateTime,e.Phar_Administr_DateTime)>40 THEN e.ENCOUNTER_NUMBER END) AS Red_gt40\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        6: f"/* NOTE: DECISION_DATETIME NULL for ARCUSAIR */\nSELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT CASE WHEN CAST(e.TRIAGE_LEVEL_CODE AS STRING) NOT IN ('1','2') AND e.DECISION_DATETIME IS NOT NULL AND LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP))!='9999-01-01'::TIMESTAMP THEN e.ENCOUNTER_NUMBER END) AS C_With_Data,\n  ROUND(AVG(CASE WHEN CAST(e.TRIAGE_LEVEL_CODE AS STRING) NOT IN ('1','2') AND LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP))!='9999-01-01'::TIMESTAMP AND DATEDIFF('minute',LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP)),COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME))>=0 THEN DATEDIFF('minute',LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP)),COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME)) END),2) AS Avg_Min,\n  COUNT(DISTINCT CASE WHEN CAST(e.TRIAGE_LEVEL_CODE AS STRING) NOT IN ('1','2') AND DATEDIFF('minute',LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP)),COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME))<120 THEN e.ENCOUNTER_NUMBER END) AS Green_lt120,\n  COUNT(DISTINCT CASE WHEN CAST(e.TRIAGE_LEVEL_CODE AS STRING) NOT IN ('1','2') AND DATEDIFF('minute',LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP)),COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME)) BETWEEN 120 AND 139 THEN e.ENCOUNTER_NUMBER END) AS Amber_120_139,\n  COUNT(DISTINCT CASE WHEN CAST(e.TRIAGE_LEVEL_CODE AS STRING) NOT IN ('1','2') AND DATEDIFF('minute',LEAST(COALESCE(e.Earliest_Lab_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Rad_Order_DateTime,'9999-01-01'::TIMESTAMP),COALESCE(e.Earliest_Phar_Order_DateTime,'9999-01-01'::TIMESTAMP)),COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME))>=140 THEN e.ENCOUNTER_NUMBER END) AS Red_ge140\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        7: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT CASE WHEN e.DISCHARGE_DATETIME IS NOT NULL THEN e.ENCOUNTER_NUMBER END) AS C_With_Data,\n  ROUND(AVG(CASE WHEN DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME)>=0 THEN DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME) END),2) AS Avg_Min,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME)<90 THEN e.ENCOUNTER_NUMBER END) AS Green_lt90,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME) BETWEEN 90 AND 109 THEN e.ENCOUNTER_NUMBER END) AS Amber_90_109,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME)>110 THEN e.ENCOUNTER_NUMBER END) AS Red_gt110\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        8: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='Home' THEN e.ENCOUNTER_NUMBER END) AS C_Home,\n  ROUND(AVG(CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='Home' AND DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME)>=0 THEN DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME) END),2) AS Avg_Min,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='Home' AND DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME)<90 THEN e.ENCOUNTER_NUMBER END) AS Green_lt90,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='Home' AND DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME) BETWEEN 90 AND 109 THEN e.ENCOUNTER_NUMBER END) AS Amber_90_109,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='Home' AND DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME)>110 THEN e.ENCOUNTER_NUMBER END) AS Red_gt110\nFROM {src} e\nLEFT JOIN {LU} d ON TRIM(e.DISCHARGE_DESTINATION)=TRIM(d.DISCHARGE_DESTINATION)\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        9: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='General Ward' THEN e.ENCOUNTER_NUMBER END) AS C_Ward,\n  ROUND(AVG(CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='General Ward' AND DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME)>=0 THEN DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME) END),2) AS Avg_Min,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='General Ward' AND DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME)<90 THEN e.ENCOUNTER_NUMBER END) AS Green_lt90,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='General Ward' AND DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME) BETWEEN 90 AND 109 THEN e.ENCOUNTER_NUMBER END) AS Amber_90_109,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='General Ward' AND DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME)>110 THEN e.ENCOUNTER_NUMBER END) AS Red_gt110\nFROM {src} e\nLEFT JOIN {LU} d ON TRIM(e.DISCHARGE_DESTINATION)=TRIM(d.DISCHARGE_DESTINATION)\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        10: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD IN ('Adult ICU','Pediatric ICU','Cardiac ICU','Neonatal ICU') THEN e.ENCOUNTER_NUMBER END) AS C_ICU,\n  ROUND(AVG(CASE WHEN d.DISCHARGE_DESTINATION_STANDARD IN ('Adult ICU','Pediatric ICU','Cardiac ICU','Neonatal ICU') AND DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME)>=0 THEN DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME) END),2) AS Avg_Min,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD IN ('Adult ICU','Pediatric ICU','Cardiac ICU','Neonatal ICU') AND DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME)<90 THEN e.ENCOUNTER_NUMBER END) AS Green_lt90,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD IN ('Adult ICU','Pediatric ICU','Cardiac ICU','Neonatal ICU') AND DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME) BETWEEN 90 AND 109 THEN e.ENCOUNTER_NUMBER END) AS Amber_90_109,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD IN ('Adult ICU','Pediatric ICU','Cardiac ICU','Neonatal ICU') AND DATEDIFF('minute',COALESCE(e.DECISION_DATETIME,e.DISCHARGE_DATETIME),e.DISCHARGE_DATETIME)>110 THEN e.ENCOUNTER_NUMBER END) AS Red_gt110\nFROM {src} e\nLEFT JOIN {LU} d ON TRIM(e.DISCHARGE_DESTINATION)=TRIM(d.DISCHARGE_DESTINATION)\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        11: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT e.ENCOUNTER_NUMBER) AS C_Visits,\n  SUM(CASE WHEN e.DISCHARGE_DATETIME IS NOT NULL AND DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,e.DISCHARGE_DATETIME)<=240 THEN 1 ELSE 0 END) AS C_Within_4hrs,\n  ROUND(SUM(CASE WHEN e.DISCHARGE_DATETIME IS NOT NULL AND DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,e.DISCHARGE_DATETIME)<=240 THEN 1 ELSE 0 END)*100.0/NULLIF(COUNT(DISTINCT CASE WHEN e.DISCHARGE_DATETIME IS NOT NULL THEN e.ENCOUNTER_NUMBER END),0),2) AS Pct_Within_4hrs\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        12: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT e.ENCOUNTER_NUMBER) AS C_Encounters,\n  ROUND(AVG(CASE WHEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,COALESCE(e.DISCHARGE_DATETIME,e.FETCH_TIMESTAMP))>=0 THEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,COALESCE(e.DISCHARGE_DATETIME,e.FETCH_TIMESTAMP)) END),2) AS Avg_ALOS_Min,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,COALESCE(e.DISCHARGE_DATETIME,e.FETCH_TIMESTAMP))<240 THEN e.ENCOUNTER_NUMBER END) AS Green_lt4hrs,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,COALESCE(e.DISCHARGE_DATETIME,e.FETCH_TIMESTAMP)) BETWEEN 240 AND 299 THEN e.ENCOUNTER_NUMBER END) AS Amber_4_5hrs,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,COALESCE(e.DISCHARGE_DATETIME,e.FETCH_TIMESTAMP))>=360 THEN e.ENCOUNTER_NUMBER END) AS Red_ge6hrs\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        13: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD IN ('Adult ICU','Pediatric ICU','Cardiac ICU','Neonatal ICU') THEN e.ENCOUNTER_NUMBER END) AS C_ICU,\n  ROUND(AVG(CASE WHEN d.DISCHARGE_DESTINATION_STANDARD IN ('Adult ICU','Pediatric ICU','Cardiac ICU','Neonatal ICU') AND DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,COALESCE(e.DISCHARGE_DATETIME,e.FETCH_TIMESTAMP))>=0 THEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,COALESCE(e.DISCHARGE_DATETIME,e.FETCH_TIMESTAMP)) END),2) AS Avg_ALOS_ICU_Min\nFROM {src} e\nLEFT JOIN {LU} d ON TRIM(e.DISCHARGE_DESTINATION)=TRIM(d.DISCHARGE_DESTINATION)\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        14: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='General Ward' THEN e.ENCOUNTER_NUMBER END) AS C_Ward,\n  ROUND(AVG(CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='General Ward' AND DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,COALESCE(e.DISCHARGE_DATETIME,e.FETCH_TIMESTAMP))>=0 THEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,COALESCE(e.DISCHARGE_DATETIME,e.FETCH_TIMESTAMP)) END),2) AS Avg_ALOS_Ward_Min\nFROM {src} e\nLEFT JOIN {LU} d ON TRIM(e.DISCHARGE_DESTINATION)=TRIM(d.DISCHARGE_DESTINATION)\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        15: "/* EMS pipeline not yet built — no EMS timestamp in any HIS source */\nSELECT 'EMS pipeline not yet built' AS STATUS",

        16: f"/* DAX fix: SUM not COUNT(DISTINCT). NULL for INTERSYSTEM. */\nSELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  SUM(COALESCE(e.LAB_ORDERS_STAT,0)) AS C_Lab_STAT,\n  ROUND(AVG(CASE WHEN e.LAB_ORDERS_STAT>0 AND e.STAT_LAB_TAT_hours IS NOT NULL AND e.STAT_LAB_TAT_hours*60>=0 THEN e.STAT_LAB_TAT_hours*60 END),2) AS Avg_Lab_TAT_STAT_Min,\n  COUNT(DISTINCT CASE WHEN e.LAB_ORDERS_STAT>0 AND e.STAT_LAB_TAT_hours*60<60 THEN e.ENCOUNTER_NUMBER END) AS Green_lt60,\n  COUNT(DISTINCT CASE WHEN e.LAB_ORDERS_STAT>0 AND e.STAT_LAB_TAT_hours*60 BETWEEN 60 AND 69 THEN e.ENCOUNTER_NUMBER END) AS Amber_60_69,\n  COUNT(DISTINCT CASE WHEN e.LAB_ORDERS_STAT>0 AND e.STAT_LAB_TAT_hours*60>70 THEN e.ENCOUNTER_NUMBER END) AS Red_gt70\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        17: f"/* DAX fix: SUM not COUNT(DISTINCT). NULL for INTERSYSTEM. */\nSELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  SUM(COALESCE(e.LAB_ORDERS_STAT,0)) AS C_Lab_STAT,\n  ROUND(AVG(CASE WHEN e.LAB_ORDERS_STAT>0 AND e.STAT_LAB_TAT_hours_UCC IS NOT NULL AND e.STAT_LAB_TAT_hours_UCC*60>=0 THEN e.STAT_LAB_TAT_hours_UCC*60 END),2) AS Avg_Lab_TAT_POCT_Min\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        18: f"/* DAX fix: SUM not COUNT(DISTINCT). NULL for INTERSYSTEM.\n   VIDAPLUS: fix STAT_RAD_STAT_hours alias typo in SW_EMERGENCY source. */\nSELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  SUM(COALESCE(e.RAD_ORDERS_STAT,0)) AS C_Rad_STAT,\n  ROUND(AVG(CASE WHEN e.RAD_ORDERS_STAT>0 AND e.STAT_RAD_TAT_hours IS NOT NULL AND e.STAT_RAD_TAT_hours*60>=0 THEN e.STAT_RAD_TAT_hours*60 END),2) AS Avg_Rad_TAT_STAT_Min,\n  COUNT(DISTINCT CASE WHEN e.RAD_ORDERS_STAT>0 AND e.STAT_RAD_TAT_hours*60<=120 THEN e.ENCOUNTER_NUMBER END) AS Green_le120,\n  COUNT(DISTINCT CASE WHEN e.RAD_ORDERS_STAT>0 AND e.STAT_RAD_TAT_hours*60 BETWEEN 121 AND 129 THEN e.ENCOUNTER_NUMBER END) AS Amber_121_129,\n  COUNT(DISTINCT CASE WHEN e.RAD_ORDERS_STAT>0 AND e.STAT_RAD_TAT_hours*60>130 THEN e.ENCOUNTER_NUMBER END) AS Red_gt130\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        19: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT e.ENCOUNTER_NUMBER) AS C_Visits,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='LAMA' THEN e.ENCOUNTER_NUMBER END) AS C_LAMA,\n  ROUND(COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='LAMA' THEN e.ENCOUNTER_NUMBER END)*100.0/NULLIF(COUNT(DISTINCT e.ENCOUNTER_NUMBER),0),2) AS Pct_LAMA\nFROM {src} e\nLEFT JOIN {LU} d ON TRIM(e.DISCHARGE_DESTINATION)=TRIM(d.DISCHARGE_DESTINATION)\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        20: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT e.ENCOUNTER_NUMBER) AS C_Visits,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='LWBS' THEN e.ENCOUNTER_NUMBER END) AS C_LWBS,\n  ROUND(COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='LWBS' THEN e.ENCOUNTER_NUMBER END)*100.0/NULLIF(COUNT(DISTINCT e.ENCOUNTER_NUMBER),0),2) AS Pct_LWBS\nFROM {src} e\nLEFT JOIN {LU} d ON TRIM(e.DISCHARGE_DESTINATION)=TRIM(d.DISCHARGE_DESTINATION)\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        21: f"diag AS (\n  SELECT e.HIS,e.FACILITY_CODE_NHIC,e.MRN,e.ENCOUNTER_NUMBER,\n         TRIM(f.value::STRING) AS ICD_CODE, e.PATIENT_VISIT_DATETIME, e.DISCHARGE_DATETIME\n  FROM {src} e,\n       TABLE(FLATTEN(INPUT=>SPLIT(COALESCE(e.PRINICIPAL_DIAGNOSIS,''),','))) f\n  WHERE TRIM(f.value::STRING)<>''\n),\nreturn_flags AS (\n  SELECT DISTINCT curr.FACILITY_CODE_NHIC,curr.MRN,curr.ENCOUNTER_NUMBER AS curr_encounter_number\n  FROM diag curr\n  JOIN diag prev ON curr.FACILITY_CODE_NHIC=prev.FACILITY_CODE_NHIC AND curr.MRN=prev.MRN AND curr.ICD_CODE=prev.ICD_CODE\n    AND prev.DISCHARGE_DATETIME<curr.PATIENT_VISIT_DATETIME\n    AND DATEDIFF('hour',prev.DISCHARGE_DATETIME,curr.PATIENT_VISIT_DATETIME)<=72\n  WHERE prev.DISCHARGE_DATETIME IS NOT NULL\n)\nSELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT e.ENCOUNTER_NUMBER) AS C_Visits,\n  COUNT(DISTINCT CASE WHEN rf.curr_encounter_number IS NOT NULL THEN e.ENCOUNTER_NUMBER END) AS C_Return_72hr,\n  ROUND(COUNT(DISTINCT CASE WHEN rf.curr_encounter_number IS NOT NULL THEN e.ENCOUNTER_NUMBER END)*100.0/NULLIF(COUNT(DISTINCT e.ENCOUNTER_NUMBER),0),2) AS Pct_Return_72hr\nFROM {src} e\nLEFT JOIN return_flags rf ON e.FACILITY_CODE_NHIC=rf.FACILITY_CODE_NHIC AND e.MRN=rf.MRN AND e.ENCOUNTER_NUMBER=rf.curr_encounter_number\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        22: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD!='DOA' THEN e.ENCOUNTER_NUMBER END) AS C_Excl_DOA,\n  COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='Deceased' THEN e.ENCOUNTER_NUMBER END) AS C_Mortality,\n  ROUND(COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD='Deceased' THEN e.ENCOUNTER_NUMBER END)*100.0/NULLIF(COUNT(DISTINCT CASE WHEN d.DISCHARGE_DESTINATION_STANDARD!='DOA' THEN e.ENCOUNTER_NUMBER END),0),2) AS Pct_Mortality\nFROM {src} e\nLEFT JOIN {LU} d ON TRIM(e.DISCHARGE_DESTINATION)=TRIM(d.DISCHARGE_DESTINATION)\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        23: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT e.ENCOUNTER_NUMBER) AS C_Visits,\n  COUNT(DISTINCT CASE WHEN CAST(e.TRIAGE_LEVEL_CODE AS STRING) IN ('4','5') THEN e.ENCOUNTER_NUMBER END) AS C_NonUrgent,\n  ROUND(COUNT(DISTINCT CASE WHEN CAST(e.TRIAGE_LEVEL_CODE AS STRING) IN ('4','5') THEN e.ENCOUNTER_NUMBER END)*100.0/NULLIF(COUNT(DISTINCT e.ENCOUNTER_NUMBER),0),2) AS Pct_NonUrgent\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",

        24: f"SELECT\n  {gc}, e.HIS, e.FACILITY_CODE_NHIC,\n  COUNT(DISTINCT CASE WHEN e.TRIAGE_DATETIME IS NOT NULL THEN e.ENCOUNTER_NUMBER END) AS C_With_Data,\n  ROUND(AVG(CASE WHEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,e.TRIAGE_DATETIME)>=0 THEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,e.TRIAGE_DATETIME) END),2) AS Avg_Min,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,e.TRIAGE_DATETIME)<15 THEN e.ENCOUNTER_NUMBER END) AS Green_lt15,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,e.TRIAGE_DATETIME) BETWEEN 16 AND 19 THEN e.ENCOUNTER_NUMBER END) AS Amber_16_19,\n  COUNT(DISTINCT CASE WHEN DATEDIFF('minute',e.PATIENT_VISIT_DATETIME,e.TRIAGE_DATETIME)>20 THEN e.ENCOUNTER_NUMBER END) AS Red_gt20\nFROM {src} e\nGROUP BY {gg}, e.HIS, e.FACILITY_CODE_NHIC\nORDER BY 1 DESC, e.HIS, e.FACILITY_CODE_NHIC",
    }

    body = Q.get(n, "SELECT 'KPI not defined' AS STATUS")
    # KPI 21 needs extra CTEs after the main CTE block
    if n == 21:
        prefix = cte_prefix(df, dt, hf, ff)
        return f"{prefix},\n{body}"
    elif n == 15:
        return body
    else:
        return f"{cte_prefix(df, dt, hf, ff)}\n{body}"


def build_date_filter(mode: str, rolling: int, date_from, date_to) -> str:
    if mode == "Rolling":
        return f"CURRENT_DATE() - {rolling}"
    return f"'{date_from}'"


def build_queries(selected_kpis, df, dt, hf, ff, g) -> str:
    parts = []
    for kpi in KPIS:
        if kpi["n"] not in selected_kpis:
            continue
        n = kpi["n"]
        tags = []
        if kpi["dax_fix"]:  tags.append("[DAX SUM fix]")
        if kpi["null_his"]: tags.append("[NULL for INTERSYSTEM]")
        tag_str = " " + " ".join(tags) if tags else ""
        sep = "=" * 66
        header = f"/* {sep}\n   KPI {n:02d} – {kpi['title']}{tag_str}\n   Source  : SW_EMERGENCY (all 8 HIS — v8)\n   Formula : {kpi['formula']}\n   Type    : {kpi['type']}\n{sep} */"
        sql = kpi_sql(n, df, dt, hf, ff, g)
        parts.append(f"{header}\n{sql}")
    return "\n\n\n".join(parts)


# ─────────────────────── UI ───────────────────────────────────────────────────

st.markdown("""
<style>
.kpi-badge { font-size:11px; padding:2px 7px; border-radius:99px; margin-left:4px; font-weight:500; }
.dax  { background:#fff3cd; color:#856404; }
.null { background:#f8d7da; color:#842029; }
</style>
""", unsafe_allow_html=True)

st.title("🏥 ED KPI Query Builder")

# ── Sidebar filters ────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("⚙️ Filters")

    his = st.selectbox("HIS system", ["ALL", "MCC", "CAREWARE", "OASIS", "VIDAPLUS", "ArcusAir", "VIDA", "INTERSYSTEM", "EPIC"])
    facility = st.text_input("Facility NHIC code", placeholder="leave blank for all")
    gran = st.selectbox("Granularity", ["Daily", "Weekly", "Monthly"])

    st.divider()
    date_mode = st.radio("Date range", ["Rolling", "Custom"], horizontal=True)
    if date_mode == "Rolling":
        rolling_days = st.selectbox("Window", [7, 14, 30, 60, 90], index=2)
        df_str = f"CURRENT_DATE() - {rolling_days}"
        dt_str = ""
        st.info(f"Filter: >= CURRENT_DATE() - {rolling_days}")
    else:
        col1, col2 = st.columns(2)
        d_from = col1.date_input("From", value=date.today() - timedelta(days=30))
        d_to   = col2.date_input("To",   value=date.today())
        df_str = f"'{d_from}'"
        dt_str = f"'{d_to}'"
        st.info(f"Filter: >= {d_from}  AND  <= {d_to}")

    st.divider()
    st.caption("**Legend**")
    st.markdown('<span class="kpi-badge dax">DAX SUM fix</span> Order count was wrong in DAX', unsafe_allow_html=True)
    st.markdown('<span class="kpi-badge null">NULL: INTERSYSTEM</span> No sub-table integration', unsafe_allow_html=True)

# ── KPI selection ──────────────────────────────────────────────────────────────
st.subheader("Select KPIs")

col_a, col_b, col_c, col_d = st.columns(4)
if col_a.button("✅ Select all"):       st.session_state["sel"] = {k["n"] for k in KPIS}
if col_b.button("🚫 Clear all"):        st.session_state["sel"] = set()
if col_c.button("⏱ Time KPIs only"):    st.session_state["sel"] = {k["n"] for k in KPIS if k["group"]=="time"}
if col_d.button("📊 Rate KPIs only"):   st.session_state["sel"] = {k["n"] for k in KPIS if k["group"]=="rate"}

if "sel" not in st.session_state:
    st.session_state["sel"] = set()

# render 4-column grid of checkboxes
cols = st.columns(4)
for i, kpi in enumerate(KPIS):
    with cols[i % 4]:
        badges = ""
        if kpi["dax_fix"]:  badges += ' <span class="kpi-badge dax">DAX</span>'
        if kpi["null_his"]: badges += ' <span class="kpi-badge null">NULL</span>'
        label = f"KPI {kpi['n']:02d} – {kpi['title']}"
        checked = st.checkbox(label, value=(kpi["n"] in st.session_state["sel"]), key=f"kpi_{kpi['n']}")
        if checked:
            st.session_state["sel"].add(kpi["n"])
        else:
            st.session_state["sel"].discard(kpi["n"])

selected = sorted(st.session_state["sel"])
st.caption(f"**{len(selected)} of 24 KPIs selected**")

# ── Generate SQL ───────────────────────────────────────────────────────────────
st.divider()
st.subheader("Generated SQL")

if not selected:
    st.info("Select at least one KPI above to generate SQL.")
else:
    ff = facility.strip() if facility.strip() and facility.strip().upper() != "ALL" else ""
    sql_out = build_queries(selected, df_str, dt_str, his, ff, gran)

    st.code(sql_out, language="sql", line_numbers=True)

    col1, col2 = st.columns([1, 5])
    col1.download_button(
        label="⬇️ Download .sql",
        data=sql_out,
        file_name=f"ed_kpi_query_{date.today()}.sql",
        mime="text/plain",
    )
    dt_label = f"  to  {dt_str}" if dt_str else ""
    col2.caption(f"Query generated for {len(selected)} KPI(s) · HIS: {his} · Gran: {gran} · Date: {df_str}{dt_label}")
